const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Agentic Infrastructure as Code Fundamentals', subtitle: 'Intent, tools, evidence, and human control.', type: 'pipeline', items: ['human|intent', 'bounded|agent', 'repository|+ tools', 'evidence', 'human|approval'], foot: 'a complete engineering system, not generated HCL', titleSlide: true},
  divider(2, 'How Infrastructure Automation Evolved'),
  content(3, 'Manual Infrastructure Work', 'Human judgment, weak repeatability.', 'hub', ['engineer', 'console|commands', 'ticket|notes', 'cloud|systems', 'memory|handoff'], 'same request, different result'),
  content(4, 'Scripts Made Procedures Repeatable', 'The procedure becomes code.', 'pipeline', ['command 1', 'command 2', 'error?', 'retry', 'cleanup'], 'every path must be programmed'),
  content(5, 'Declarative Infrastructure as Code', 'Describe the result, then inspect the plan.', 'pipeline', ['desired|state', 'dependency|graph', 'provider|refresh', 'plan', 'review'], 'create · update · replace · delete'),
  content(6, 'AI-Augmented IaC', 'The model suggests; the engineer drives.', 'loop', ['ask', 'suggest', 'human|edit', 'human|run', 'read|result'], 'the human starts every step'),
  content(7, 'Agentic IaC', 'A bounded system acts and responds to evidence.', 'loop', ['goal', 'inspect', 'act', 'observe', 'verify', 'evidence'], 'tools + feedback + stop conditions'),
  content(8, 'The Automation Evolution', 'Each stage keeps the useful parts below it.', 'ladder', ['manual', 'scripts', 'declarative|IaC', 'AI|augmented', 'agentic|IaC'], 'agentic workflows still depend on deterministic IaC', true),
  divider(9, 'What Is Agentic Infrastructure as Code?'),
  content(10, 'Agentic IaC Defined by Behaviour', 'Seven behaviours define the system.', 'hub', ['bounded agent', 'intent', 'trusted|context', 'plan', 'approved|tools', 'observe', 'verify|stop'], 'product names can change; the behaviour remains', true),
  content(11, 'Agency and Autonomy Are Different', 'Capability and authority are separate.', 'compare', ['AGENCY', 'inspect · plan|act · observe', 'AUTONOMY', 'files · tools|credentials · approval'], 'strong agency can run with low autonomy'),
  content(12, 'Automation, AI Assistance, and Agency', 'Three different control models.', 'cards', ['fixed automation|predefined path', 'AI assistance|human connects steps', 'agentic workflow|feedback-driven path'], 'choose the model that fits the work'),
  divider(13, 'AI-Augmented IaC and Agentic IaC'),
  content(14, 'AI-Augmented Provider Repair', 'The engineer owns every transition.', 'pipeline', ['validate|error', 'ask model', 'copy draft', 'human edit', 'human run'], 'helpful suggestion, human-driven workflow'),
  content(15, 'Agentic Provider Repair', 'The agent owns approved steps, then stops.', 'pipeline', ['task|contract', 'inspect', 'edit one|file', 'validate', 'evidence'], 'apply is outside the boundary', true),
  content(16, 'Action Requires Stronger Controls', 'Control grows with consequence.', 'ladder', ['suggest', 'read', 'edit', 'network', 'apply', 'delete'], 'ask what each tool call can change'),
  divider(17, 'Coding Agents, Operational Agents, and Autonomy'),
  content(18, 'Coding Agents Work with Repositories', 'Isolation makes change reviewable.', 'boundary', ['coding agent', 'allowed files', 'worktree', 'CLI checks', 'Git diff'], 'short-lived repository task'),
  content(19, 'Operational Agents Work Across Time', 'Repeated access changes the risk.', 'loop', ['schedule', 'read live|evidence', 'compare', 'report', 'escalate'], 'read-only · fresh evidence · kill switch'),
  content(20, 'The Autonomy Ladder', 'Higher is not automatically better.', 'ladder', ['L0|manual', 'L1|suggest', 'L2|plan', 'L3|bounded', 'L4|approved', 'L5|observe'], 'choose authority based on the task', true),
  content(21, 'Choose the Lowest Useful Level', 'Match task to authority.', 'cards', ['explain → L1', 'assess → L2', 'repair → L3', 'deliver → L4', 'drift report → L5', 'unsafe request → REJECT'], 'most coding labs stop at L3'),
  divider(22, 'Anatomy of an Agentic IaC System'),
  content(23, 'Six Working Parts', 'The model is one component.', 'hub', ['agentic IaC', 'intent', 'context', 'plan', 'tools', 'evidence', 'control'], 'a weak part weakens the whole system'),
  content(24, 'Intent', 'Make success observable.', 'compare', ['VAGUE', 'make it|scalable', 'BOUNDED', 'job ID < 1s|public API unchanged'], 'outcome + acceptance + non-goals'),
  content(25, 'Trusted Context', 'Select current, source-linked facts.', 'pipeline', ['repo|rules', 'module|contract', 'current|policy', 'runtime|evidence', 'task|bundle'], 'reject stale notes and injected comments'),
  content(26, 'Reasoning and Plan', 'Expose assumptions before large changes.', 'pipeline', ['facts', 'assumptions', 'affected|files', 'checks', 'approval|points'], 'a plan shows intention, not proof'),
  content(27, 'Tools', 'The interface defines real authority.', 'hub', ['tool boundary', 'schema', 'arguments', 'identity', 'directory', 'network', 'timeout'], 'be careful is not a permission control'),
  content(28, 'Evidence', 'Link every claim to the exact artifact.', 'pipeline', ['claim', 'commit +|artifact', 'command', 'exit code +|output', 'review'], 'old evidence does not prove new code'),
  content(29, 'Control', 'Guardrails shape every step.', 'boundary', ['agent + tools', 'files + tools', 'credentials', 'budgets + retry', 'approval + stop'], 'enforce instructions with validators'),
  content(30, 'Agentic IaC System Architecture', 'Reasoning operates inside an engineering system.', 'hub', ['human + agent', 'trusted|context', 'approved|tools', 'repo +|test env', 'state +|read-only data', 'evidence', 'policy +|approval'], 'the model cannot repair unsafe system design', true),
  divider(31, 'The Agent Loop for Infrastructure Changes'),
  content(32, 'Understand, Plan, Act, Observe, Verify', 'A controlled feedback path.', 'loop', ['understand', 'plan', 'act', 'observe', 'verify', 'evidence'], 'observation and verification are different', true),
  content(33, 'Understand and Plan', 'Start with facts; mark assumptions.', 'pipeline', ['task|contract', 'repo rules', 'current|failure', 'assumptions', 'plan +|stop'], 'ask before crossing the boundary'),
  content(34, 'Act and Observe', 'Use the smallest action that tests the plan.', 'compare', ['ACTION', 'one-file edit|approved command', 'OBSERVE', 'direct output|failure category'], 'tool output may change the plan'),
  content(35, 'Verify and Return Evidence', 'Acceptance checks close the task.', 'pipeline', ['fmt', 'Terraform|validate', 'OpenTofu|validate', 'changed-file|check', 'evidence|bundle'], 'name what remains unverified'),
  content(36, 'Retry, Stop, or Escalate', 'Every loop needs clear exits.', 'cards', ['repair in scope|retry budget remains', 'same failure repeats|STOP', 'new file needed|ESCALATE', 'unsafe tool needed|ESCALATE'], 'no unlimited retries', true),
  divider(37, 'Why Infrastructure Agents Need Stronger Guardrails'),
  content(38, 'Terraform State Is a Trust Boundary', 'State binds an address to a real object.', 'pipeline', ['HCL|address', 'state|binding', 'provider', 'real|resource'], 'state operations can change identity'),
  content(39, 'Credentials and Network Reach', 'Capability radius must match the task.', 'compare', ['NARROW', 'one environment|read or validate', 'BROAD', 'admin identity|any endpoint'], 'shortest useful identity and reach'),
  content(40, 'Destructive Actions and Blast Radius', 'Review impact, not line count.', 'pipeline', ['two-line|diff', 'shared|module', '10 envs', 'replace +|delete', 'high review'], 'unused cannot be inferred locally'),
  content(41, 'Approval, Recovery, and Observation', 'Apply success is not service success.', 'pipeline', ['exact diff|+ plan', 'human|approval', 'delivery', 'observe', 'recover'], 'approval expires when the artifact changes'),
  content(42, 'Task Contract Anatomy', 'Turn boundaries into explicit fields.', 'cards', ['objective', 'allowed files|+ tools', 'forbidden|actions', 'required|evidence', 'stop|conditions', 'human|approval'], 'compact interface between intent and authority', true),
  divider(43, 'CLI, MCP, Agent Skills, and Workflow Harnesses'),
  content(44, 'CLI', 'Portable execution and evidence.', 'pipeline', ['exact|command', 'bounded|args', 'exit code', 'captured|output', 'CI + human|replay'], 'shell access still needs limits'),
  content(45, 'MCP', 'Structured access through a server boundary.', 'pipeline', ['agent|client', 'tool/resource|schema', 'MCP|server', 'narrow|system'], 'structure does not create trust'),
  content(46, 'Agent Skills', 'Version a repeated engineering procedure.', 'pipeline', ['metadata', 'instructions', 'references', 'scripts', 'tests + owner'], 'reviewed operational code'),
  content(47, 'Workflow Harnesses', 'Coordinate the engineering process.', 'pipeline', ['spec', 'plan', 'isolate', 'build + test', 'review', 'verify'], 'Superpowers is one portable example', true),
  content(48, 'Choose the Capability Boundary', 'Use the smallest interface that works.', 'cards', ['deterministic check|CLI', 'structured source|read-only MCP', 'repeated procedure|Skill', 'full workflow|harness', 'destructive judgment|human'], 'every integration adds maintenance and risk'),
  divider(49, 'A Governed Agentic IaC Change, End to End'),
  content(50, 'Requirement, Task Contract, and Context', 'Start with outcome, authority, and facts.', 'pipeline', ['validate with|two tools', 'one allowed|file', 'no apply|or state', 'current error|+ repo rules'], 'the agent knows the goal and boundary', true),
  content(51, 'Plan and One-File Change', 'Preserve behaviour with the smallest repair.', 'pipeline', ['declare|provider', 'add random_id|resource', 'keep output|behaviour', 'one-file|diff'], 'green syntax must not remove intent'),
  content(52, 'Initialization Is an Environment State', 'Classify the failure before editing again.', 'compare', ['ERROR', 'provider not|installed', 'DECISION', 'init without|backend'], 'not every failed check means bad code'),
  content(53, 'Terraform and OpenTofu Verification', 'Each supported tool produces evidence.', 'compare', ['TERRAFORM', 'init -backend=false|validate PASS', 'OPENTOFU', 'init -backend=false|validate PASS'], 'compatibility is tested, not assumed'),
  content(54, 'Review, Stop, and Record Evidence', 'The task ends at proof, not apply.', 'pipeline', ['Git diff', 'changed-file|boundary', 'two validators', 'clean cache', 'STOP'], 'no generated files · no apply'),
  divider(55, 'The Project and the Course Workflow'),
  content(56, 'Production AI Workload Platform', 'A small workload with realistic infrastructure.', 'pipeline', ['client', 'API|job ID', 'queue', 'worker|mock inference', 'result +|job state'], 'no GPU or model API required'),
  content(57, 'Infrastructure and Delivery Boundaries', 'Each tool owns a different lifecycle.', 'cards', ['Terraform|cloud-shaped base', 'Helm|workload package', 'Kubernetes|runtime state', 'Argo CD|reconciliation', 'Actions|plan + approval', 'Hermes|read-only observe'], 'one agent does not own everything'),
  content(58, 'Low-Resource Lab Strategy', 'Use the smallest profile needed.', 'pipeline', ['tested|reference', 'one active|profile', 'small Kind|cluster', 'cleanup|before next', 'warning|not a gate'], '7 GB guides the lab design; it does not reject the learner'),
  content(59, 'The Course Project Progression', 'Every section leaves a reviewable artifact.', 'ladder', ['foundation', 'context +|tools', 'Terraform +|tests', 'Kubernetes +|GitOps', 'Hermes +|capstone'], 'one project grows through the course'),
  content(60, 'Agentic IaC Foundation Complete', 'You can explain, bound, and review the system.', 'hub', ['ready for lab', 'evolution', 'agency +|autonomy', 'six parts', 'agent loop', 'guardrails', 'tool choice'], 'next: prove the foundation yourself'),
  content(61, 'Next: Prepare the Agentic IaC Workspace', 'Five human steps, one clean starting point.', 'icons', ['locate', 'preflight', 'discover', 'inspect', 'compare'], '', true),
];
