const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false, aria = '') => ({n, title, subtitle, type, items, foot, fragments, aria});

export const lectureTitles = [
  'Git as a Change and Approval Boundary',
  'Pull Requests, CODEOWNERS, and Branch Protection',
  'GitHub Actions Trust and Workflow Security',
  'Terraform Plan and Controlled Apply',
  'How Argo CD Reconciliation Works',
  'Promotion and Environment Boundaries',
  'Sync Order, Health, and Failure Recovery',
  'Rollback, Roll Forward, and Drift',
  'Delivery Evidence and Separation of Duties',
];

export const slides = [
  content(1, 'Deliver Infrastructure Safely with GitOps and Human Approval', 'One reviewed commit. Two delivery lanes. Human authority.', 'twoLanes', ['reviewed commit', 'plan-only|Terraform/OpenTofu', 'manual|Argo CD sync', 'human|approval'], 'agents prepare evidence · humans authorize change', false, 'One reviewed commit splits into a plan-only Terraform or OpenTofu lane and a manually synchronized Argo CD lane; both stop at a human approval boundary.'),

  divider(2, lectureTitles[0]),
  content(3, 'Git Records Bytes, Not Authority', 'A stable object is not permission.', 'compare', ['COMMIT SHA', 'exact tree + parent', 'AUTHORIZATION', 'actor + purpose + action'], 'Git identity does not approve delivery'),
  content(4, 'Four Identities Keep One Change Honest', 'Each identity owns one narrow responsibility.', 'cards', ['AUTHOR|propose change', 'REVIEWER|accept risk', 'WORKFLOW|run checks', 'RUNTIME|serve workload'], 'no identity approves its own privilege'),
  content(5, 'Credentials Follow the Identity Boundary', 'Give each role only the authority it needs.', 'hub', ['bounded|credentials', 'author|source write', 'reviewer|approval', 'workflow|read + check', 'runtime|service access'], 'shared credentials collapse the boundary', true),
  content(6, 'One Commit Enters Two Delivery Lanes', 'Both lanes start from the reviewed revision.', 'splitCommit', ['commit|1e01929', 'plan-only|workflow', 'Argo CD|desired state', 'human|decision'], 'one source identity · different delivery mechanics', true, 'Commit 1e01929 branches to a plan-only workflow and an Argo CD desired-state path; each reaches a separate human decision gate.'),
  content(7, 'Same Tree Does Not Mean Same History', 'A revert restores bytes with a new commit.', 'pipeline', ['v1 commit|tree A', 'v2 commit|tree B', 'revert commit|tree A'], 'same desired bytes · different event in history', true),
  content(8, 'Approval Binds Actor, Purpose, and Commit', 'The decision record needs exact scope.', 'cards', ['ACTOR|human reviewer', 'PURPOSE|promote v2', 'COMMIT|full SHA', 'ACTION|sync target', 'TIME|bounded window', 'TARGET|inference'], 'a tag named approved is not enough'),

  divider(9, lectureTitles[1]),
  content(10, 'A Pull Request Is a Review Workspace', 'Rules decide whether its signals can be bypassed.', 'boundary', ['pull request|head SHA', 'diff', 'discussion', 'checks', 'approvals', 'merge rule'], 'workspace + enforcement = approval boundary'),
  content(11, 'CODEOWNERS Routes Risk to the Right Reviewer', 'Ownership follows the changed path.', 'hub', ['changed|paths', 'Terraform|platform network', 'Helm|workload platform', 'workflow|delivery security'], 'requested review must also be required', true),
  content(12, 'Branch Rules Turn Signals into Gates', 'The protected branch moves only after every gate.', 'pipeline', ['latest|head SHA', 'required|checks', 'required|owners', 'stale approval|dismissed', 'restricted|merge'], 'all gates bind to the same commit', true),
  content(13, 'Required Checks Bind to the Head SHA', 'A later push invalidates earlier evidence.', 'compare', ['COMMIT A', 'checks green', 'COMMIT B', 'new bytes · rerun'], 'green A cannot approve B'),
  content(14, 'Split Payload Changes from Judge Changes', 'A candidate must not rewrite its evaluator.', 'compare', ['PAYLOAD PR', 'Terraform + Helm', 'CONTROL PR', 'privileged workflow'], 'different owners · different trust path'),
  content(15, 'Merge Evidence Names Both Tested Revisions', 'A merge queue may create another commit.', 'pipeline', ['PR head|SHA', 'required|checks', 'merge candidate|SHA', 'protected|branch'], 'preserve head and delivered revision', true),

  divider(16, lectureTitles[2]),
  content(17, 'Event Context Sets the First Trust Boundary', 'Trusted context must not execute untrusted fork code.', 'compare', ['pull_request', 'untrusted code|read-only context', 'pull_request_target', 'trusted base|metadata only'], 'event choice changes token and secret risk'),
  content(18, 'Trusted Evaluator Bytes Judge Untrusted PR Bytes', 'The candidate supplies input, not the judge.', 'trustBoundary', ['trusted|workflow SHA', 'untrusted|candidate diff', 'fixed|evaluator', 'bounded|report'], 'candidate bytes never replace evaluator bytes', false, 'The trusted workflow SHA loads a fixed evaluator outside the untrusted candidate boundary, then the evaluator reads the candidate diff and produces a bounded report.'),
  content(19, 'Token Permissions Start Read-Only', 'A plan job does not need write authority.', 'ladder', ['contents|read', 'checks|report', 'artifact|write only', 'deployment|none'], 'add permission only for a named job'),
  content(20, 'Pin Every Executable Action by Commit', 'Mutable tags can move without review.', 'compare', ['MUTABLE TAG', 'actions/checkout@v4', 'FULL COMMIT SHA', 'reviewed action bytes'], 'pinning reduces silent supply-chain change'),
  content(21, 'Untrusted Text Never Becomes a Shell Program', 'Pass fixed arguments and validate data.', 'pipeline', ['event|text', 'environment|field', 'allow-list|validation', 'fixed|command'], 'quoting alone is not the boundary', true),
  content(22, 'Plan Artifacts Need Integrity and Confidentiality', 'A digest proves identity, not secrecy.', 'compare', ['INTEGRITY', 'SHA-256 + source', 'CONFIDENTIALITY', 'restricted path + retention'], 'saved plans may contain clear-text values'),
  content(23, 'A Protected Environment Gates the Trusted Job', 'Secrets appear only after a bound decision.', 'pipeline', ['untrusted|plan job', 'sanitized|summary', 'human|environment gate', 'trusted|consumer', 'scoped|secret'], 'approval rechecks commit and artifact digest', true),

  divider(24, lectureTitles[3]),
  content(25, 'Terraform Uses a Transaction-Shaped Workflow', 'Apply is a separate state-changing action.', 'pipeline', ['reviewed|config', 'state +|refresh', 'plan', 'human|approval', 'controlled|apply'], 'plan describes actions · approval authorizes action', true),
  content(26, 'One Real Plan Proposes One Create Action', 'The action comes from plan JSON.', 'planJson', ['terraform_data.reviewed_delivery', 'create', 'apply_permitted: false'], 'one semantic action · no apply', false, 'A plan JSON card names terraform_data.reviewed_delivery with the create action and apply_permitted set to false.'),
  content(27, 'The Evidence Report Binds Exact Inputs', 'Review the action and its source together.', 'cards', ['SOURCE|full commit', 'WORKFLOW|SHA-256', 'ENGINE|name + version', 'PLAN|SHA-256', 'PLAN JSON|SHA-256', 'ACTIONS|one create'], 'apply_permitted: false'),
  content(28, 'Terraform and OpenTofu Can Agree Semantically', 'Different bytes can express the same action.', 'compare', ['TERRAFORM 1.14.8', 'one create|plan hash A', 'OPENTOFU 1.12.6', 'one create|plan hash B'], 'compare required semantics · retain byte differences'),
  content(29, 'Saved Plans Can Contain Sensitive Values', 'Review access and apply access are different.', 'boundary', ['restricted|saved plan', 'encrypted store', 'short retention', 'audit access', 'sanitized summary', 'approved addresses'], 'hashing does not hide a secret'),
  content(30, 'Stale Inputs Reject an Approved Plan', 'Any changed binding needs a fresh decision.', 'hub', ['reject stale|plan', 'source moved', 'workflow moved', 'variables changed', 'target changed', 'policy changed', 'state changed'], 'approval applies to recorded inputs only', true),
  content(31, 'Human Approval Names One Exact Apply Decision', 'Broad reusable approval is not controlled apply.', 'cards', ['ACTOR|accountable human', 'PURPOSE|named change', 'TARGET|named environment', 'COMMIT|full SHA', 'PLAN|exact digest', 'EXPIRY|short window'], 'one decision · one target · one artifact'),
  content(32, 'Controlled Apply Is Explained, Not Run', 'The course stops at the state-change boundary.', 'boundary', ['controlled|apply', 'narrow identity', 'serialized state', 'unknown action reject', 'logs retained', 'precondition stop'], 'plan-only path proved · apply not executed'),

  divider(33, lectureTitles[4]),
  content(34, 'Git Holds Desired State; Kubernetes Holds Live State', 'Reconciliation observes both systems.', 'converge', ['reviewed Git|revision', 'live Kubernetes|objects', 'desired/live|diff'], 'two observations feed one comparison', false, 'The reviewed Git revision and live Kubernetes objects both flow into one desired-versus-live diff.'),
  content(35, 'Refresh Resolves the Reviewed Revision', 'A moving ref becomes one exact commit.', 'pipeline', ['repository|URL', 'targetRevision|HEAD', 'refresh', 'resolved full|commit'], 'record status.sync.revision', true),
  content(36, 'Diff Finds Tracked Desired-to-Live Differences', 'Difference is an observation, not a verdict.', 'compare', ['Synced', 'tracked fields match', 'OutOfSync', 'tracked difference exists'], 'diff does not decide safe or unsafe'),
  content(37, 'Explicit Sync Starts the Delivery Operation', 'Automated sync is absent in the course path.', 'pipeline', ['approved|commit', 'human|sync decision', 'Argo CD|operation', 'live|objects'], 'approval comes before each sync', true),
  content(38, 'Health and Operation Phase Answer Different Questions', 'Read both before making a delivery claim.', 'compare', ['HEALTH', 'Healthy or Degraded', 'OPERATION', 'Succeeded or Failed'], 'success now can become degraded later'),
  content(39, 'Application Evidence Completes the Runtime Claim', 'Controller status does not prove the user path.', 'ladder', ['Synced', 'Healthy', 'Succeeded', 'job-0001', 'complete', 'GITOPS|DELIVERY'], 'add a direct application result', true),
  content(40, 'Prune and Self-Heal Change Authority', 'Both controls are absent in the tested path.', 'compare', ['PRUNE', 'remove absent objects', 'SELF-HEAL', 'correct live drift'], 'automation needs a reviewed risk policy'),
  content(41, 'Terraform Transacts; Argo Reconciles', 'The lanes fail and recover differently.', 'transactionLoop', ['plan', 'approved apply', 'desired Git', 'diff', 'sync', 'observe'], 'one transaction ends · one loop continues', false, 'The Terraform lane moves from plan to one approved apply transaction, while the Argo CD lane cycles from desired Git through diff, sync, and repeated observation.'),

  divider(42, lectureTitles[5]),
  content(43, 'v1 and v2 Are Distinct Image Identities', 'A tag alone is not immutability proof.', 'compare', ['s10-v1', 'local image ID A', 's10-v2', 'local image ID B'], 'production promotion prefers a digest'),
  content(44, 'Fixture HEAD Is Not Production Immutability', 'Always record the full revision Argo resolved.', 'compare', ['COURSE FIXTURE', 'gated HEAD|read-only mirror', 'PRODUCTION', 'full SHA or protected ref|resolved SHA'], 'HEAD is a name · resolved commit is identity'),
  content(45, 'Promotion Changes Intent, Not Artifact Bytes', 'Move one immutable identity through environments.', 'pipeline', ['artifact|digest', 'development|intent', 'reviewed|promotion', 'staging|intent', 'production|intent'], 'a rebuild creates a different artifact', true),
  content(46, 'Each Environment Owns Policy and Credentials', 'Development access does not inherit production access.', 'cards', ['APPLICATION|chart + version', 'PLATFORM|cluster + project', 'SECURITY|workflow + secret', 'ENVIRONMENT|approval + target'], 'owners meet at a reviewed promotion change'),
  content(47, 'Promotion Evidence Binds Commit, Artifact, and Target', 'Approval names both bytes and destination.', 'converge', ['reviewed|commit', 'artifact|digest', 'environment|identity'], 'one promotion decision binds all three', false, 'The reviewed commit and immutable artifact digest converge on one named environment identity.'),
  content(48, 'Manual Live Changes Become Drift', 'Durable promotion changes the source of truth.', 'compare', ['kubectl set image', 'live state only|future drift', 'reviewed Git change', 'desired state|reconciled'], 'emergency action needs a Git follow-up'),

  divider(49, lectureTitles[6]),
  content(50, 'Dependencies Define the Safe Sync Order', 'Order follows a real requirement.', 'pipeline', ['namespace +|platform', 'configuration +|identity', 'workload', 'ready|endpoint', 'application|request'], 'object creation order is not readiness proof', true),
  content(51, 'Sync Waves Group Ordered Resources', 'Lower integers run before higher integers.', 'ladder', ['wave|-10', 'wave|0', 'wave|10', 'health|gate'], 'use waves only for real dependencies', true),
  content(52, 'Hooks Are Executable Delivery Logic', 'Treat each hook like a small production program.', 'boundary', ['sync hook', 'lifecycle phase', 'narrow identity', 'idempotent action', 'timeout + retry', 'cleanup policy'], 'ordering availability does not make a hook safe'),
  content(53, 'Health Stops the Next Promotion', 'A degraded environment blocks progression.', 'pipeline', ['current|environment', 'Degraded', 'STOP', 'diagnose|evidence', 'new|decision'], 'do not advance on controller warning', true),
  content(54, 'Partial Failure Changes the Retry Decision', 'Old ready replicas can preserve service.', 'compare', ['OLD REVISION', 'ready replicas|still serving', 'NEW REVISION', 'missing image|Degraded'], 'inspect partial state before retry'),
  content(55, 'Recovery Rechecks Revision, Health, and Request', 'Repeat the failed path and the user path.', 'pipeline', ['approved|repair', 'sync|Succeeded', 'health|Healthy', 'revision|matches', 'request|complete'], 'recovery needs controller and application evidence', true),

  divider(56, lectureTitles[7]),
  content(57, 'Drift Is a Difference, Not a Diagnosis', 'OutOfSync reports what changed, not why.', 'compare', ['DESIRED', 'replicas: 1', 'OBSERVED', 'replicas: 2'], 'identify owner and cause before correction'),
  content(58, 'Self-Heal Off Preserves the Observed Drift', 'Argo reports drift but does not correct it.', 'driftLoop', ['Git|replicas 1', 'live|replicas 2', 'OutOfSync', 'human|inspect'], 'two replicas remain during observation', false, 'Git replicas 1 differs from live replicas 2; Argo reports OutOfSync and stops at a human inspection because self-heal is disabled.'),
  content(59, 'Git Revert Creates a New Recovery Commit', 'The recovery tree matches v1, not its history.', 'pipeline', ['v1|tree A', 'v2|tree B', 'revert v2|tree A'], 'failed change and correction remain visible', true),
  content(60, 'Explicit Sync Reconciles the Recovery Revision', 'A revert changes runtime only after sync.', 'pipeline', ['approved|revert SHA', 'explicit|sync', 'Synced', 'Healthy', 'Succeeded', 's10-v1'], 'reconciliation acts on the new history', true),
  content(61, 'Recovery Choice Follows the Active Owner', 'Use the mechanism that owns current state.', 'hub', ['current|owner', 'GitOps|revert or forward', 'direct Helm|rollback or upgrade', 'Terraform|refresh + recovery plan', 'runtime|bounded repair + Git'], 'inspect state before choosing a command', true),
  content(62, 'Roll Forward When Old State Is No Longer Safe', 'Data or schema can block a simple revert.', 'compare', ['REVERT', 'old state remains compatible', 'ROLL FORWARD', 'new correction|fresh review'], 'recovery is a system decision, not a preference'),

  divider(63, lectureTitles[8]),
  content(64, 'One Evidence Trail Connects Nine Records', 'No single record proves the whole delivery.', 'evidenceTrail', ['request', 'commit', 'checks', 'reviewer', 'approval', 'artifact', 'operation', 'observation', 'cleanup'], 'each record supports one bounded claim', true, 'A forward evidence trail links request, commit, checks, reviewer, approval, artifact, delivery operation, runtime observation, and cleanup.'),
  content(65, 'Typed Links State the Exact Relationship', 'A relation is provenance, not automatic truth.', 'evidenceGraph', ['plan|report', 'commit|SHA', 'approval|record', 'sync|operation', 'runtime|observation', 'delivery|claim'], 'DERIVED_FROM · AUTHORIZES · SUPPORTS', false, 'A small evidence graph links the plan report to the commit with DERIVED_FROM, approval to sync with AUTHORIZES, and runtime observation to the delivery claim with SUPPORTS.'),
  content(66, 'Every Evidence Record Has a Proof Limit', 'Use each observation for its own claim.', 'cards', ['PLAN|proposed actions', 'CONTROLLER|sync + health', 'RUNTIME|observed result', 'CLEANUP|named absence'], 'none proves the others'),
  content(67, 'Separation of Duties Blocks Authority Loops', 'No actor grants and uses its own privilege.', 'authorityBoundary', ['agent|proposes', 'workflow|checks', 'human|reviews', 'human|approves', 'delivery|acts'], 'direct author-to-delivery path is forbidden', false, 'A forward path moves from agent proposes through workflow checks, human review, human approval, and delivery; a crossed-out bypass from the agent directly to delivery is forbidden.'),
  content(68, 'The Final Replay Closes the Bounded Claim', 'Measured course evidence, not a universal promise.', 'cards', ['COMMANDS|61 passed', 'PLAN|one create', 'ARGO|v1 + v2 + recovery', 'REQUEST|job complete', 'PEAK|1.680 GiB', 'CLEANUP|exact absence'], 'Terraform/OpenTofu apply never ran'),

  content(69, 'Reviewed Bytes Move; Human Authority Stays Separate', 'Agents prepare evidence. Humans authorize change.', 'twoLanes', ['reviewed commit', 'plan-only|evidence', 'Argo CD|reconciliation', 'human|authority'], 'runtime proof remains a separate observation', false),
  content(70, 'Plan, Promote, Recover, and Close the Evidence', 'Run both safe lanes and remove the runtime.', 'icons', ['inspect|starter', 'repair +|plan', 'approve|v1', 'promote|v2', 'drift +|recover', 'verify +|clean'], 'local Kind · no cloud · no apply'),
];
