const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Build Your First IaC Change with an AI Coding Agent', subtitle: 'One safe repair. Direct proof. Human review.', type: 'pipeline', items: ['human|request', 'task|contract', 'coding|agent', 'one-file|change', 'direct|evidence', 'human|review'], foot: 'Terraform + OpenTofu · no infrastructure change', titleSlide: true},
  divider(2, 'How Do You Turn an IaC Request into an Agent Task?'),
  content(3, 'A Request Is Not Yet a Task', '"Fix the Terraform" leaves important questions open.', 'hub', ['fix the Terraform', 'which|failure?', 'which|files?', 'which|tools?', 'what is|success?', 'when to|stop?'], 'a concern is not an executable task'),
  content(4, 'A Task Makes Success Testable', 'Write the result, limits, checks, and stop point.', 'pipeline', ['request', 'objective', 'work|boundary', 'required|checks', 'stop|condition'], 'another person can review the task before work starts', true),
  content(5, 'The Task Lives with the Code', 'The same task file works across coding agents.', 'hub', ['section-2/task.md', 'Codex', 'Claude|Code', 'Goose', 'Cursor', 'Copilot|or VS Code'], 'the interface changes; the repository contract remains'),
  divider(6, 'What Is an IaC Task Contract?'),
  content(7, 'The First Half of the Task Contract', 'Define the result and the working area.', 'cards', ['objective|observable result', 'inputs|trusted facts', 'work boundary|owned files'], 'start with what the agent may trust and change'),
  content(8, 'The Second Half of the Task Contract', 'Define authority, proof, and clear exits.', 'cards', ['allowed tools|read · edit · validate', 'forbidden actions|state · delete · destroy', 'required evidence|diff · output · exit', 'stop conditions|return control'], '"be careful" is not a control'),
  content(9, 'File Scope and Tool Scope Are Different', 'Both boundaries are required.', 'compare', ['FILE SCOPE', 'one allowed file|no unrelated edits', 'TOOL SCOPE', 'inspect + validate|no state change'], 'a one-file task can still call an unsafe tool'),
  content(10, 'Stop When the Task Needs More Authority', 'A scope change needs a new decision.', 'pipeline', ['one-file|task', 'second file|required', 'STOP', 'human|decision'], 'stopping is the correct result', true),
  divider(11, 'What Should an IaC Agent Inspect Before It Changes Code?'),
  content(12, 'Five Views Before the First Edit', 'Build a current view of the work.', 'cards', ['repository|rules', 'affected|configuration', 'state + network|boundary', 'exact|failure', 'working|tree'], 'inspection protects the whole repository'),
  content(13, 'Start with the Exact Failure', 'The output supports one narrow repair.', 'compare', ['REFERENCE', 'random_id.platform.hex|is used', 'DECLARATION', 'random_id.platform|is missing'], 'add the missing resource; keep the output'),
  content(14, 'Code Failure or Environment Failure?', 'Classify the result before changing code again.', 'compare', ['CODE', 'undeclared|resource', 'ENVIRONMENT', 'registry DNS|not available'], 'different failures need different responses'),
  content(15, 'Protect Existing Human Work', 'Isolate the candidate and review its diff.', 'pipeline', ['clean|base', 'existing|human work', 'isolated|worktree', 'agent|candidate', 'one-file|diff'], 'do not hide or overwrite another change'),
  divider(16, 'How Do Plans, Assumptions, and Human Checkpoints Work?'),
  content(17, 'Facts and Assumptions Need Different Treatment', 'Cite facts. Confirm or reject assumptions.', 'compare', ['FACTS', 'reference exists|resource absent', 'ASSUMPTIONS', 'byte length = 4|one lock works'], 'facts come from inspection; assumptions need a decision'),
  content(18, 'Keep the Repair Plan Short', 'Five steps are enough for this repair.', 'pipeline', ['inspect', 'edit one|file', 'validate', 'review|diff', 'STOP'], 'the plan exposes checks and the finish line', true),
  content(19, 'A Plan Is Not Proof', 'Intent and completion are different.', 'compare', ['PLAN', 'what should|happen', 'EVIDENCE', 'what did|happen'], 'a plan cannot replace a diff or command result'),
  content(20, 'Pause Before the Risk Class Changes', 'Local validation does not approve deployment.', 'apply-block', ['local edit', 'local validation', 'human checkpoint', 'state change'], 'new authority needs a new approval'),
  divider(21, 'How Does a Safe IaC Agent Change Loop Work?'),
  content(22, 'The Safe Change State Machine', 'Only approved transitions exist.', 'state-machine', ['proposed', 'authorized', 'changed', 'validated', 'approved', 'stopped', 'rejected'], 'there is no transition to a state-changing action', false),
  content(23, 'Apply Has No Transition', 'The current task cannot reach deployment.', 'apply-block', ['task boundary', 'validated change', 'STOP', 'APPLY'], 'an action outside the graph requires another task'),
  content(24, 'Retry Only While the Error Stays in Scope', 'Use a small retry budget.', 'pipeline', ['check|fails', 'error is|in scope?', 'retry|1 of 2', 'small|repair', 'run check|again'], 'stop when the same failure repeats', true),
  content(25, 'Stop or Escalate on Boundary Changes', 'Return control instead of adding authority.', 'cards', ['same failure|repeats → STOP', 'new file|required → ASK', 'credential|prompt → STOP', 'live system|needed → NEW TASK'], 'a blocked path is useful evidence'),
  divider(26, 'What Evidence Proves an IaC Agent Change?'),
  content(27, 'Agent Summary and Direct Evidence', 'Review the artifacts behind the claim.', 'compare', ['SUMMARY', '"validation passed"|agent claim', 'DIRECT EVIDENCE', 'command + cwd|exit + output + diff'], 'the summary explains; the artifacts prove'),
  content(28, 'Evidence Needs Identity', 'Bind every result to the exact input.', 'pipeline', ['commit or|file hash', 'command +|working dir', 'tool|version', 'exit +|raw output', 'review|decision'], 'old evidence does not prove new code', true),
  content(29, 'Each Check Proves One Thing', 'Read every green result within its limit.', 'cards', ['fmt|file shape', 'validate|references + types', 'Git diff|tracked change', 'command log|actions run'], 'combine checks only after naming each limit'),
  content(30, 'Codex Authored; the Host Proved', 'Keep the sandbox and host results separate.', 'compare', ['CODEX SANDBOX', 'one-file repair|DNS stop', 'HOST TERMINAL', 'six checks pass|62.3 MiB max RSS'], 'do not claim Codex ran the host checks'),
  content(31, 'Terraform and OpenTofu Need Separate Proof', 'The lock source can change between tools.', 'compare', ['TERRAFORM', 'registry.terraform.io|random 3.9.0', 'OPENTOFU', 'registry.opentofu.org|hashes rewritten'], 'one shared lock file is not compatibility proof'),
  divider(32, 'How Do You Recover from an Unsafe Agent Proposal?'),
  content(33, 'Reject an Unauthorized Apply', 'A valid file does not approve a state change.', 'apply-block', ['valid configuration', 'unsafe proposal', 'REJECT', 'AUTO APPROVE'], 'name the exact boundary that was crossed'),
  content(34, 'Recover in Six Controlled Steps', 'Return to the last trusted checkpoint.', 'pipeline', ['reject', 'inspect', 'preserve', 'restore|task', 'return|evidence', 'new task|later'], 'do not widen permission during recovery', true),
  content(35, 'Preserve the Safe Candidate', 'Keep useful work in its isolated worktree.', 'boundary', ['reviewable candidate', 'one-file diff', 'validation|results', 'unsafe proposal|rejected', 'no merge|or deploy'], 'reject the action, not valid work'),
  content(36, 'Delivery Is a Separate Task', 'Deployment needs its own controls.', 'pipeline', ['validated|candidate', 'delivery|task', 'environment +|credentials', 'plan +|approval', 'observe +|recover'], 'repair and delivery are separate decisions'),
  divider(37, 'How Do You Repair Terraform with an AI Coding Agent?'),
  content(38, 'Portable Artifacts Keep the Workflow Agent Neutral', 'Use files and CLI evidence as the stable interface.', 'hub', ['portable workflow', 'task.md', 'starter|main.tf', 'Terraform|CLI', 'OpenTofu|CLI', 'Git|diff'], 'the coding agent is replaceable'),
  content(39, 'The Smallest Correct Terraform Repair', 'Add the missing resource and keep the output.', 'terraform-repair', ['resource "random_id" "platform"', 'byte_length = 4', 'output.platform_name', 'random_id.platform.hex'], 'four added lines restore the required reference', true),
  content(40, 'Validate with Two IaC Engines', 'Each engine produces independent evidence.', 'compare', ['TERRAFORM', 'fmt → init|validate PASS', 'OPENTOFU', 'fmt → init|validate PASS'], 'both initializations disable the backend', true),
  content(41, 'Accept the Change, Then Stop', 'Complete the evidence checkpoint.', 'pipeline', ['one-file|diff', 'six checks|pass', 'lock warning|recorded', 'no state|file', 'STOP'], 'reviewable proof closes this task', true),
  content(42, 'Your First Agentic IaC Change Is Ready for Review', 'You can guide, check, and stop the repair.', 'hub', ['ready for review', 'task|contract', 'inspection', 'bounded|change', 'direct|evidence', 'human|checkpoint'], 'next: run the same workflow yourself'),
  content(43, 'Next: Repair and Prove the Terraform Change', 'Six human steps, one reviewable result.', 'icons', ['inspect', 'reproduce', 'ask Codex', 'review diff', 'validate', 'stop'], '', true),
];
