const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Connect Your IaC Agent to Tools, Skills, and MCP', subtitle: 'Give the agent only the capability this task needs.', type: 'title-story', items: ['human task', 'capability gate', 'Skill', 'fixed CLI', 'MCP resource', 'evidence', 'human review'], foot: 'reasoning proposes · bounded capabilities act', fragments: true, titleSlide: true},
  divider(2, 'Capability Boundaries for Agents'),
  content(3, 'Reasoning Does Not Change Infrastructure', 'The model proposes; another layer performs the action.', 'compare', ['MODEL', 'describes the next step', 'CAPABILITY', 'reads, writes, or runs'], 'different roles · different risk'),
  content(4, 'Five Layers Carry Different Responsibility', 'Follow the path from task to real system access.', 'pipeline', ['human task', 'model', 'agent host', 'adapter', 'operating system'], 'approval stays outside the model', true),
  content(5, 'Effective Authority Is an Intersection', 'The narrowest boundary decides what can happen.', 'authority-intersection', ['task scope', 'admitted capability', 'runtime permissions', 'approval state'], 'all four must permit the action', true),
  content(6, 'A Safe Description Is Not a Safety Control', 'Claims explain intent; controls deny unsafe behaviour.', 'compare', ['CLAIM', '“review only”', 'CONTROL', 'fixed argv + no network'], 'inspect where denial really happens'),
  content(7, 'Human Approval Remains a Real Boundary', 'Validation can run; infrastructure change waits.', 'approval-gate', ['validate', 'evidence', 'human review', 'plan or apply'], 'approval pending', true),

  divider(8, 'CLI, API, MCP, Skill, or Manual Step?'),
  content(9, 'Choose the Route by the Work', 'Start with the task shape, not a favourite tool.', 'five-routes', ['CLI', 'API', 'MCP', 'Skill', 'manual'], 'five routes · five different jobs', true),
  content(10, 'CLI Fits a Stable Local Operation', 'Exact arguments and exit codes make evidence portable.', 'route-focus', ['stable executable', 'fixed arguments', 'local evidence'], 'queue review: fmt + init + validate'),
  content(11, 'API Fits a Remote Service Contract', 'Use it when identity, quota, or service semantics matter.', 'route-focus', ['remote service', 'request schema', 'scoped identity'], 'not needed for this local review'),
  content(12, 'MCP Fits Discoverable Context or Tools', 'A client discovers a narrow server capability.', 'route-focus', ['server discovery', 'resources', 'tools'], 'transport does not decide trust'),
  content(13, 'A Skill Fits a Reusable Procedure', 'Package instructions and supporting artifacts together.', 'route-focus', ['discovery', 'procedure', 'reference + script'], 'procedure is not permission'),
  content(14, 'Keep High-Risk Judgment Manual', 'People retain exception and irreversible authority.', 'route-focus', ['risk decision', 'approval record', 'named owner'], 'manual is a deliberate route'),

  divider(15, 'CLI as the Portable Execution and Evidence Plane'),
  content(16, 'An Open Shell Leaves Too Many Choices', 'Every free field can widen the task.', 'hub', ['agent command', 'executable', 'arguments', 'directory', 'environment', 'timeout', 'output'], 'unbounded process creation', true),
  content(17, 'The Command Contract Removes Choices', 'Fix the fields before the agent can run anything.', 'controlled-cli', ['terraform|or tofu', 'fixed argv', 'fixture copy', '30 seconds', 'minimal env', 'new evidence|file'], 'course control · not a tool standard', true),
  content(18, 'Fixed Argument Arrays Block Command Injection', 'Data cannot become a second command.', 'compare', ['OPEN TEXT', 'terraform <model text>', 'FIXED ARRAY', '["validate", "-no-color"]'], 'shell = false'),
  content(19, 'A Temporary Copy Narrows File Access', 'Validate one file without touching the repository source.', 'pipeline', ['main.tf', 'temporary copy', 'terraform or tofu', 'result'], 'source bytes remain unchanged', true),
  content(20, 'A Minimal Environment Withholds Credentials', 'Do not pass secrets the task does not need.', 'compare', ['AMBIENT ENV', 'cloud tokens + package keys', 'CHILD ENV', 'PATH + automation flags'], 'redaction is only defence in depth'),
  content(21, 'Evidence Binds to the Exact Run', 'Record inputs, versions, hashes, output, and result.', 'evidence-chain', ['source hash', 'contract hash', 'engine version', 'argv + exit codes', 'stdout + stderr', 'PASS or FAIL'], 'replayable and reviewable', true),
  content(22, 'A Green Validation Has Clear Limits', 'State what the run did not prove.', 'pass-boundary', ['PASS: local validation', 'no provider lock proof', 'no cloud plan', 'no deployment approval'], 'portable does not mean unrestricted'),

  divider(23, 'Build an Agent Skill for Terraform Review'),
  content(24, 'A Skill Is a Directory With SKILL.md', 'The official format starts with one required file.', 'skill-anatomy', ['terraform-review/', 'SKILL.md', 'references/', 'scripts/', 'tests/'], 'tests are a course addition'),
  content(25, 'Skill Frontmatter Supports Discovery', 'Name and description tell a client when it may help.', 'cards', ['name|terraform-review', 'description|bounded IaC review', 'compatibility|Node 20+', 'metadata|owner + version'], 'official fields · reviewed values'),
  content(26, 'Progressive Disclosure Loads Three Layers', 'Load detail only after the Skill becomes relevant.', 'progressive-disclosure', ['name + description', 'SKILL.md procedure', 'reference + script'], 'metadata → instructions → resources', true),
  content(27, 'The Procedure Names Inputs and Outputs', 'A reusable procedure still needs a strict contract.', 'compare', ['INPUTS', 'engine + evidence filename', 'OUTPUTS', 'version + hashes + exits'], 'no command text or arbitrary path'),
  content(28, 'Stop Conditions Prevent Scope Drift', 'The Skill stops when the request needs more authority.', 'boundary', ['terraform review', 'network', 'credentials', 'state', 'plan', 'apply'], 'unsafe request → stop'),
  content(29, 'allowed-tools Is a Hint, Not Enforcement', 'Client support varies; runtime controls still decide.', 'compare', ['SKILL METADATA', 'intended tools', 'RUNTIME', 'process + file + network denial'], 'official experimental field · course enforcement'),
  content(30, 'The Skill Calls the Fixed Runner', 'Procedure and execution remain separate layers.', 'pipeline', ['Skill selected', 'read procedure', 'approved script', 'fixed runner', 'evidence'], 'each hand-off stays reviewable', true),

  divider(31, 'Test, Version, Own, and Revoke Skills'),
  content(32, 'Review the Complete Reachable Package', 'SKILL.md can point to code and detailed instructions.', 'dependency-closure', ['SKILL.md', 'reference', 'runner script', 'command contract', 'MCP server'], 'pin every controlling artifact', true),
  content(33, 'Version Names a Release; Hash Names Bytes', 'You need both a human label and exact identity.', 'compare', ['VERSION', '1.0.0', 'SHA-256', 'exact reviewed bytes'], 'same version + new bytes = drift'),
  content(34, 'Ownership Makes Repair Accountable', 'Every admitted capability needs a responsible maintainer.', 'cards', ['OWNER|course-maintainers', 'SCOPE|local review', 'VERSION|1.0.0', 'CONTACT|repository review'], 'no owner → no admission'),
  content(35, 'Test Failure Paths Before Admission', 'Prove rejection as well as the happy path.', 'test-matrix', ['unknown engine', 'extra argument', 'path escape', 'overwrite', 'secret output', 'forbidden operation'], 'negative tests expose hidden freedom'),
  content(36, 'No-Network Replay Tests the Boundary', 'A denied network is stronger evidence than a promise.', 'pipeline', ['network denied', 'run Skill tests', 'run both engines', 'capture PASS'], 'measured path stayed local', true),
  content(37, 'Revocation Removes Trust First', 'Changed assumptions require a new admission.', 'revocation-loop', ['hash drift', 'remove admission', 'investigate', 'repair + retest', 're-admit'], 'never update a hash just to make green', true),

  divider(38, 'MCP for Narrow Context and Tool Access'),
  content(39, 'MCP Separates Host, Client, and Server', 'The host controls which server reaches a session.', 'mcp-architecture', ['human', 'agent host', 'MCP client', 'local server', 'queue resource'], 'JSON-RPC over local stdio', true),
  content(40, 'Discover Before You Use', 'The server reports one narrow capability.', 'pipeline', ['server/discover', '2026-07-28', 'resources only', 'resources/list', 'resources/read'], 'no tools capability', true),
  content(41, 'Resources Provide Context', 'A resource returns data for the client to read.', 'resource-flow', ['iac://course/queue-review', 'Markdown', 'source path', 'SHA-256 + bytes'], 'read-only does not mean trusted'),
  content(42, 'Tools Can Perform an Operation', 'A tool call may cross from context into action.', 'tool-flow', ['tools/list', 'tool schema', 'tools/call', 'real side effect'], 'sensitive calls need consent'),
  content(43, 'Resource and Tool Are Different Primitives', 'Choose context when the task does not need action.', 'compare', ['RESOURCE', 'list + read data', 'TOOL', 'list + call function'], 'protocol shape is not authorization'),
  content(44, 'Negative Probes Show the Narrow Boundary', 'Unknown calls should fail closed.', 'cards', ['unknown URI|-32602', 'missing metadata|-32602', 'unknown method|-32601', 'tools capability|absent'], 'failure behaviour is evidence'),
  content(45, 'MCP Mechanics and Course Controls Differ', 'Keep protocol facts separate from local trust policy.', 'compare', ['MCP SPEC', 'messages + discovery', 'COURSE CONTROL', 'hashes + sandbox + approval'], 'server identity is self-reported'),

  divider(46, 'Tool and Skill Supply-Chain Threats'),
  content(47, 'A Valid Package Can Still Be Unsafe', 'Correct format says nothing about requested authority.', 'compare', ['VALID FORMAT', 'name + schema + annotations', 'UNSAFE AUTHORITY', 'shell + secrets + apply'], 'admit behaviour, not labels'),
  content(48, 'Poisoned Metadata Tries to Win Trust', 'A description can hide or request unsafe behaviour.', 'poisoned-metadata', ['“read only”', 'delete or apply', '“upload repo first”', 'credential request'], 'metadata is untrusted input'),
  content(49, 'Tool Annotations Are Hints', 'The server reports them; the server can misreport them.', 'compare', ['readOnlyHint: true', 'selection signal', 'implementation mutates', 'runtime reality'], 'official warning · trust separately'),
  content(50, 'Unpinned Startup Changes Without Review', 'latest can resolve to different bytes tomorrow.', 'pipeline', ['package@latest', 'new package bytes', 'same config', 'new authority'], 'pin or vendor reviewed code', true),
  content(51, 'A Trusted Host Can Become a Confused Deputy', 'Bind every sensitive call to trusted intent.', 'deputy-gate', ['untrusted request', 'trusted host', 'admitted capability', 'approval state', 'bounded call'], 'authority must match the caller and task', true),
  content(52, 'Supply-Chain Review Continues After Install', 'Ownership, updates, tests, and revocation stay active.', 'revocation-loop', ['publisher change', 'schema expands', 'hash mismatch', 'revoke', 'review again'], 'trust is a lifecycle', true),

  divider(53, 'Agent Adapters Without Vendor Lock-In'),
  content(54, 'Repository Artifacts Hold the Durable Workflow', 'Keep policy and evidence outside any one agent UI.', 'cards', ['task contract', 'Agent Skill', 'CLI contract', 'MCP server + probe', 'trust record', 'tests + evidence'], 'portable acceptance contract'),
  content(55, 'An Adapter Maps a Client to the Same Contract', 'Codex demonstrates; other agents use the same artifacts.', 'adapter-boundary', ['Codex', 'Claude Code', 'Goose', 'Cursor / VS Code', 'common contract'], 'only discovery and invocation differ', true),
  content(56, 'Adapter Authority Must Stay Smaller', 'Client integration cannot expand the task.', 'boundary', ['client adapter', 'no broad shell', 'no extra network', 'no secrets', 'no auto-apply'], 'adapter maps; policy stays stable'),
  content(57, 'Deterministic Admission Checks Exact Identity', 'Bytes, authority, tests, owner, and approval converge.', 'admission-gate', ['artifact hashes', 'requested authority', 'tests + probe', 'owner + version', 'human decision'], 'default deny on drift or excess', true),
  content(58, 'The Capability Pack Connects Narrow Paths', 'Skill, CLI, and MCP converge into evidence.', 'capability-pack', ['portable task', 'client|adapter', 'reviewed|Skill', 'fixed CLI', 'MCP|resource', 'independent|gates', 'human|review'], 'no plan or apply path', true),
  content(59, 'Give the Agent Less Power and Better Evidence', 'Select the smallest route. Enforce it. Prove the run.', 'closing', ['smallest route', 'runtime controls', 'exact evidence', 'human approval'], 'reasoning helps · controls decide', true),
  content(60, 'Build the Bounded Capability Pack', 'Inspect, reject, build, test, review, then stop.', 'lab-bridge', ['inspect request', 'run CLI', 'build Skill', 'probe MCP', 'reject unsafe', 'review evidence'], 'no infrastructure change', true),
];
