const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Build, Test, and Optimize Reliable IaC Agent Workflows', subtitle: 'Put a repeatable control system around the model.', type: 'title-story', items: ['request', 'contract', 'isolated|run', 'observed|evidence', 'four|gates', 'Run Card', 'human|review'], foot: 'one-off prompt → measurable engineering workflow', fragments: true, titleSlide: true},
  divider(2, 'What Is an Agent Workflow Harness?'),
  content(3, 'A Good Prompt Is Not a Workflow', 'One useful answer does not create repeatability or recovery.', 'compare', ['ONE-OFF PROMPT', 'model answer', 'WORKFLOW HARNESS', 'bounded run + evidence'], 'the model sits inside the system'),
  content(4, 'Six Layers Surround the Model', 'Each layer owns a different control.', 'pipeline', ['specification', 'plan', 'isolation', 'execution', 'evaluation', 'recovery'], 'every hand-off is reviewable', true),
  content(5, 'The Harness Owns the Loop', 'Inspect, act, observe, and revise only inside limits.', 'hub', ['agent loop', 'writable paths', 'tool allowlist', 'attempt limit', 'time limit', 'evidence', 'stop conditions'], 'open-ended reasoning · bounded execution', true),
  content(6, 'Workflow State Must Be Explicit', 'A command result cannot silently become approval.', 'pipeline', ['designed', 'approved to run', 'running', 'evidence ready', 'rejected or review'], 'state changes need named events', true),
  content(7, 'Stop Conditions Are Safe Outcomes', 'Missing authority or evidence should stop the run.', 'boundary', ['task in scope', 'missing tool', 'path escape', 'network needed', 'approval missing'], 'unsupported request → stop'),
  content(8, 'PASS Means Ready for Human Review', 'Evaluation supports a decision; it does not deploy.', 'approval-gate', ['four gates PASS', 'Run Card', 'human review', 'next action'], 'identity + consent + approval stay external', true),

  divider(9, 'Superpowers-Style Workflow Patterns'),
  content(10, 'Use a Portable Engineering Sequence', 'The practice survives a change of coding agent.', 'pipeline', ['brainstorm', 'approve design', 'write plan', 'isolate', 'test first', 'verify'], 'skills guide the process · controls enforce it', true),
  content(11, 'Design Before a Wide IaC Diff', 'Answer lifecycle, authority, evidence, and recovery first.', 'cards', ['LIFECYCLE|what changes?', 'AUTHORITY|what may run?', 'EVIDENCE|what proves it?', 'RECOVERY|how return?'], 'approved design narrows implementation'),
  content(12, 'A Written Plan Creates Checkpoints', 'Small tasks make review and repair cheaper.', 'pipeline', ['task 1', 'evidence 1', 'task 2', 'evidence 2', 'integration'], 'one bounded gate at a time', true),
  content(13, 'Isolation Preserves the Baseline', 'Give the candidate its own history and directory.', 'compare', ['SHARED WORKTREE', 'user edits + agent edits', 'ISOLATED WORKTREE', 'candidate branch only'], 'never repair the canonical starter in place'),
  content(14, 'Test First Proves the Evaluator Can See', 'A red result must exist before the repair.', 'compare', ['BEFORE', 'seeded failure → RED', 'AFTER', 'small repair → GREEN'], 'red · green · refactor'),
  content(15, 'Adapters Map to One Contract', 'Codex demonstrates; compatible agents use the same gates.', 'adapter-boundary', ['Codex', 'Claude Code', 'Goose', 'Cursor / VS Code', 'portable task + tests'], 'invocation changes · acceptance stays stable', true),

  divider(16, 'Isolation, Checkpoints, and Recovery'),
  content(17, 'Branch and Worktree Solve Different Problems', 'History and directory isolation work together.', 'compare', ['BRANCH', 'separate Git history', 'WORKTREE', 'separate working directory'], 'neither is a process sandbox'),
  content(18, 'A Temporary Copy Protects the Fixture', 'Every run starts from immutable source bytes.', 'pipeline', ['fixture main.tf', 'temporary copy', 'workflow operations', 'CLI checks', 'run evidence'], 'canonical input stays unchanged', true),
  content(19, 'Process Controls Narrow Execution', 'Exact argv removes choices the task does not need.', 'controlled-cli', ['terraform|or tofu', 'fixed argv', 'shell false', '30 seconds', 'small env', 'local logs'], 'no plan · no apply · no state', true),
  content(20, 'A Checkpoint Binds State and Evidence', 'Name the exact task, source, run, suite, and decision.', 'evidence-chain', ['task hash', 'fixture hash', 'plan hash', 'suite hash', 'changed files', 'gate results'], 'Git history plus Run Card', true),
  content(21, 'Capture Failure Before Cleanup', 'Evidence explains what to repair next.', 'pipeline', ['command fails', 'classify failure', 'write Run Card', 'review', 'guarded cleanup'], 'do not erase the diagnosis', true),
  content(22, 'Recovery Names One Reversible Action', 'Discard, restore, or revert the exact target.', 'approval-gate', ['rejected run', 'preserve evidence', 'human decision', 'restore checkpoint'], 'never reset unrelated user work', true),

  divider(23, 'Evaluation Design for Agentic IaC'),
  content(24, 'Every Evaluation Tests a Claim', 'Connect the claim to a fixture, observation, and threshold.', 'pipeline', ['claim', 'fixture', 'observation', 'threshold', 'failure id', 'recovery'], 'a green label alone explains nothing', true),
  content(25, 'Four Gates Define Acceptance', 'All required gates pass; none compensates for another.', 'hub', ['accepted run', 'functional', 'safety', 'regression', 'budget'], 'logical AND · not one weighted score', true),
  content(26, 'Seed Failures That Matter', 'The weak run contains real function and real violations.', 'pipeline', ['extra context', 'forbidden file', '12 commands', 'retry allowance', 'function still passes'], 'designed false green', true),
  content(27, 'The Weak Suite Tells a Narrow Truth', 'One enabled gate passes while two classes remain hidden.', 'compare', ['WEAK RESULT', 'PASS 1/1', 'COMPLETE RESULT', 'REJECTED 2/4'], 'true result · incomplete decision'),
  content(28, 'Set Thresholds Before the Candidate', 'Do not move the budget just to make green.', 'cards', ['context|≤ 120', 'output|≤ 300', 'commands|≤ 3', 'retries|0', 'estimate|≤ $0.01'], 'threshold changes need separate review'),
  content(29, 'Rubrics Need Observable Anchors', 'Judgment becomes reviewable when levels are concrete.', 'cards', ['0|missing', '1|vague retry', '2|named restore', '3|owner + validation'], 'calibrate with examples'),
  content(30, 'Mutation Tests Test the Evaluator', 'Change one protected behaviour and require the right failure.', 'pipeline', ['valid HCL', 'change queue default', 'run regression gate', 'regression.summary', 'discard mutation'], 'bad case must fail for the right reason', true),

  divider(31, 'Functional, Safety, and Regression Evals'),
  content(32, 'Functional: Did the Repair Work?', 'The exact fixed commands and queue result must pass.', 'route-focus', ['nullable false', 'fmt + init + validate', 'functional.result'], 'necessary · not sufficient'),
  content(33, 'Safety: Did the Run Stay in Scope?', 'Observe bytes instead of trusting the agent summary.', 'compare', ['SELF REPORT', '“only main.tf”', 'DERIVED DIFF', 'main.tf + notes file'], 'safety.scope rejects the baseline'),
  content(34, 'Regression: Did the Default Stay Stable?', 'Valid Terraform can still change behaviour.', 'compare', ['EXPECTED', 'queue_name=course-jobs', 'OBSERVED', 'derived from main.tf'], 'regression.summary names the difference'),
  content(35, 'Budget: Did Useful Work Stay Bounded?', 'Measure context, output, commands, retries, and estimate.', 'test-matrix', ['context', 'output', 'commands', 'retries', 'time', 'estimated cost'], 'budget is a gate · not decoration'),
  content(36, 'Independent Gates Reduce Correlated Error', 'Different claims need different observations.', 'hub', ['run evidence', 'CLI exits', 'byte diff', 'golden summary', 'numeric telemetry'], 'one false summary cannot make every gate green', true),
  content(37, 'Missing Evidence Fails Closed', 'Unknown is not PASS.', 'pass-boundary', ['REJECT: evidence missing', 'no inferred scope', 'no invented exit', 'no assumed approval'], 'repair evaluator or environment first'),

  divider(38, 'Run Telemetry and Failure Classification'),
  content(39, 'Telemetry Follows the Workflow Events', 'Capture facts at each state change.', 'pipeline', ['task accepted', 'tool started', 'tool completed', 'file changed', 'gate result', 'review requested'], 'events need run id + outcome', true),
  content(40, 'Raw Log and Run Card Serve Different Needs', 'Keep detail local; carry compact review evidence.', 'compare', ['RAW LOG', 'stdout + stderr + timings', 'RUN CARD', 'hashes + counts + gates'], 'compact does not mean unverifiable'),
  content(41, 'The Run Card Binds the Exact Run', 'Inputs, observations, limits, and decision converge.', 'evidence-chain', ['five hashes', 'changed files', 'command telemetry', 'four gates', 'failure classes', 'human boundary'], 'ready for review · not approved', true),
  content(42, 'Failure Classes Guide Recovery', 'Name the kind of problem before choosing the response.', 'cards', ['FUNCTIONAL|repair result', 'SAFETY|stop + narrow', 'REGRESSION|inspect change', 'BUDGET|remove waste', 'ENVIRONMENT|repair setup', 'EVALUATOR|repair checks'], 'do not call every failure agent failure'),
  content(43, 'Trace Privacy Is a Design Requirement', 'Collect the minimum useful evidence.', 'boundary', ['raw trace', 'no env values', 'redact secrets', 'access policy', 'retention'], 'more telemetry can create more risk'),
  content(44, 'Typed Links Preserve Provenance', 'State exactly how evidence relates to a claim.', 'pipeline', ['command record', 'SUPPORTS', 'CLI claim', 'Run Card', 'DERIVED FROM'], 'links are reviewable · not automatic truth', true),

  divider(45, 'Token and Cost Engineering'),
  content(46, 'Manage Five Connected Budgets', 'Tokens are one part of workflow cost.', 'hub', ['workflow budget', 'context', 'output', 'retries', 'time + concurrency', 'money'], 'include model + tools + infrastructure + people', true),
  content(47, 'Select Context by Task Need', 'More text can add cost and conflict without adding evidence.', 'compare', ['BASELINE', 'selected + noisy = 416', 'CANDIDATE', 'selected only = 90'], 'keep required policy · remove unrelated reference'),
  content(48, 'Compare Whole Runs, Not One Metric', 'The accepted run improves without weakening a gate.', 'cards', ['GATES|2 → 4', 'FILES|2 → 1', 'COMMANDS|12 → 3', 'CONTEXT|416 → 90', 'FAILURES|2 classes → none'], 'same function + regression result'),
  content(49, 'Estimate and Bill Are Different Fields', 'Precision does not create accuracy.', 'compare', ['COURSE ESTIMATE', 'bytes ÷ 4 + fixed rate', 'PROVIDER BILL', 'reported tokens + current price'], 'label source + model + version'),
  content(50, 'FinOps Includes More Than Model Tokens', 'Infrastructure and operator effort can dominate.', 'cards', ['model usage', 'hosted tools', 'preview cloud', 'storage + network', 'review time', 'recovery time'], 'attribute cost to owner + task'),
  content(51, 'Budget Limits Can Stop or Escalate', 'Do not truncate required evidence to stay green.', 'approval-gate', ['budget near limit', 'stop safely', 'human selects context', 'resume checkpoint'], 'blocked for decision is honest', true),

  divider(52, 'RTK, Caveman, and Evaluation-Driven Optimization'),
  content(53, 'RTK Compacts Agent-Facing Command Output', 'Raw evidence remains available for audit.', 'pipeline', ['command', 'raw local record', 'RTK filter', 'compact context', 'same gates'], 'output presentation changes · result does not', true),
  content(54, 'Compression Must Preserve Diagnosis', 'A smaller output that hides the error is a regression.', 'compare', ['KEEP', 'exit + error + file + line', 'REJECT', 'short summary without cause'], 'measure savings and failure detection'),
  content(55, 'Caveman-Style Experiments Use Evals', 'Compare baseline and candidate, then retain or discard.', 'revocation-loop', ['name weakness', 'small experiment', 'run fixed evals', 'compare', 'retain or discard'], 'no measured gain → no change', true),
  content(56, 'Choose the Smallest Relevant Change', 'Target the observed uncertainty.', 'hub', ['next experiment', 'second agent', 'larger context', 'new Skill', 'better validator'], 'the mutation validator tests the known gap', true),
  content(57, 'One Metric Can Be Gamed', 'Optimization cannot trade away engineering value.', 'compare', ['LOWER TOKENS', 'but missing evidence', 'ACCEPTED RUN', 'all four gates + lower cost'], 'Goodhart: inspect the underlying outcome'),
  content(58, 'Two Runs Tell the Whole Story', 'Fast is useful only after function, safety, and regression.', 'compare', ['WEAK RUN', 'functional · unsafe · wasteful', 'ACCEPTED RUN', '4/4 · bounded · reviewable'], 'evidence decides · not confidence'),
  content(59, 'Make Agent Work Repeatable and Measurable', 'Specify, isolate, execute, evaluate, recover.', 'closing', ['portable contract', 'bounded tools', 'independent gates', 'honest telemetry', 'human approval'], 'the control system makes the model useful', true),
  content(60, 'Build and Evaluate the Two Runs', 'Reproduce the false green, repair three files, compare evidence.', 'lab-bridge', ['inspect|weak plan', 'run|baseline', 'enable|four gates', 'repair|workflow', 'compare|Run Cards', 'stop|for review'], 'no model or infrastructure change required', true),
];
