const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Build Infrastructure with Terraform, OpenTofu, and AI Agents', subtitle: 'Understand the engine before you trust generated HCL.', type: 'title-story', items: ['HCL', 'evaluate', 'dependency|graph', 'provider|plan', 'state|binding', 'evidence', 'human|approval'], foot: 'one resource address · complete lifecycle', fragments: true, titleSlide: true},

  divider(2, 'Terraform and OpenTofu in This Course'),
  content(3, 'Separate Language, Engine, and Provider', 'Three layers can change independently.', 'pipeline', ['HCL|language', 'Terraform or|OpenTofu', 'AWS|provider', 'remote|API'], 'same HCL does not prove same behaviour', true),
  content(4, 'Both Tools Follow a Common Loop', 'The shared mental model supports one engineering method.', 'pipeline', ['load config', 'install provider', 'build graph', 'create plan', 'apply', 'record state'], 'common loop · exact behaviour still tested', true),
  content(5, 'Compatibility Is an Evidence Claim', 'Name the versions, fixture, actions, and result.', 'evidence-chain', ['tool version', 'provider lock', 'plan actions', 'state result', 'direct APIs', 'cleanup'], 'tested scope · not a universal promise', true),
  content(6, 'Use Separate Working Copies', 'Each tool owns its generated dependency identity.', 'compare', ['TERRAFORM COPY', 'registry.terraform.io', 'OPENTOFU COPY', 'registry.opentofu.org'], 'do not hide registry rewriting'),
  content(7, 'One State Has One Writer', 'Compatibility does not authorize concurrent mutation.', 'approval-gate', ['compare read', 'review plan', 'stop old writer', 'approve new writer'], 'write authority transfers explicitly', true),

  divider(8, 'How Terraform Evaluates Configuration'),
  content(9, 'All .tf Files Form One Configuration', 'Filenames organize source for people, not execution.', 'compare', ['FILES', 'main.tf + outputs.tf', 'MODULE', 'one evaluated body'], 'the graph controls order'),
  content(10, 'Values Have Different Knowledge States', 'Unknown is typed and connected, not empty.', 'cards', ['KNOWN|from configuration', 'UNKNOWN|computed later', 'SENSITIVE|hidden display', 'NULL|explicit absence'], 'classify before approval'),
  content(11, 'Provider Schemas Give Resources Meaning', 'Parsing HCL is only the first check.', 'pipeline', ['parse HCL', 'load schema', 'validate args', 'plan behaviour'], 'required · optional · computed · replacement', true),
  content(12, 'Planning Compares Four Inputs', 'Desired code is only one source of truth.', 'evidence-inputs', ['planned change', 'configuration', 'prior state', 'remote read', 'provider logic'], 'the provider interprets the transition', true),
  content(13, 'A Saved Plan Binds Review to Apply', 'Apply the inspected actions, not a fresh calculation.', 'pipeline', ['create plan', 'inspect JSON', 'human review', 'apply saved plan'], 'evidence is still time-limited', true),
  content(14, 'Read Actions as Types', 'Counts alone hide engineering consequence.', 'cards', ['CREATE|new identity', 'UPDATE|same identity', 'REPLACE|new + old', 'MOVE|same remote object', 'READ|observe', 'DELETE|remove'], 'interpret every important action'),
  content(15, 'Each Stage Proves a Different Claim', 'Validation cannot stand in for lifecycle evidence.', 'pipeline', ['format', 'validate', 'test', 'plan', 'apply', 'direct read', 'cleanup'], 'match claim to observation', true),

  divider(16, 'The Resource Dependency Graph'),
  content(17, 'References Create Implicit Edges', 'Data flow tells Terraform what must wait.', 'pipeline', ['storage|bucket ARN', 'identity|module input', 'IAM|policy'], 'exact reference · exact dependency', true),
  content(18, 'The Foundation Has Five Owners', 'Independent domains meet through narrow interfaces.', 'hub', ['root module', 'storage', 'messaging', 'job state', 'identity', 'logs'], 'five modules · eight resources', true),
  content(19, 'Independent Nodes Run in Parallel', 'Only real data dependencies should serialize work.', 'hub', ['scheduler', 'storage', 'messaging', 'job state', 'logs'], 'identity waits for exact ARNs', true),
  content(20, 'depends_on Is an Escape Hatch', 'Use it only when data cannot express a real edge.', 'compare', ['IMPLICIT EDGE', 'exact output reference', 'EXPLICIT EDGE', 'broad depends_on'], 'broad edges create more unknowns'),
  content(21, 'Unknown Values Flow Along Edges', 'Follow consumers to find approval impact.', 'pipeline', ['bucket ARN|unknown', 'policy document|unknown', 'IAM change|review blocked'], 'unknown authority is not approval', true),
  content(22, 'A Cycle Is an Ownership Problem', 'Retry and extra dependencies cannot create a valid start.', 'revocation-loop', ['bucket needs role', 'role needs policy', 'policy needs bucket', 'redesign owner'], 'break the information cycle', true),
  content(23, 'A Graph Hash Is Limited Evidence', 'Identity is useful only with expected nodes and edges.', 'compare', ['HASH MATCH', 'same rendered graph', 'GRAPH REVIEW', 'right owners + edges'], 'hash identity ≠ graph quality'),

  divider(24, 'Provider Versions, Locks, and Reproducibility'),
  content(25, 'Three Version Controls Work Together', 'CLI, acceptable provider range, and exact package differ.', 'cards', ['required_version|engine range', 'required_providers|source + range', '.terraform.lock.hcl|version + hashes'], 'each answers a different question'),
  content(26, 'An Open Range Selected New Behaviour', 'Valid HCL silently moved beyond the proven provider.', 'compare', ['STARTER', '>= 6.0.0 → 6.62.0', 'CANDIDATE', '~> 6.61.0 → 6.61.0'], 'reproducibility is visible'),
  content(27, 'The Lock Records Package Identity', 'Source, selected version, constraints, and hashes travel together.', 'pipeline', ['source', 'version', 'constraints', 'checksums'], 'review the generated diff', true),
  content(28, 'A Checksum Is Not a Safety Review', 'It verifies bytes against a record, not provider quality.', 'compare', ['CHECKSUM', 'package identity', 'ENGINEERING REVIEW', 'behaviour + risk'], 'identity evidence has a boundary'),
  content(29, 'The Root Owns Final Selection', 'Child modules declare compatibility; the executable root locks.', 'pipeline', ['child ranges', 'root constraint', 'dependency solve', 'root lock'], 'avoid impossible exact child pins', true),
  content(30, 'Upgrade in a Dedicated Change', 'Do not mix provider behaviour with unrelated infrastructure edits.', 'pipeline', ['read notes', 'upgrade lock', 'compare plan', 'run lifecycle', 'record rollback'], 'latest is not acceptance', true),
  content(31, 'Registry Sources Can Differ', 'Same provider version produced distinct lock identity.', 'compare', ['TERRAFORM', 'lock SHA 3db541e4…', 'OPENTOFU', 'lock SHA 5be4dc35…'], 'record difference · never text-normalize'),

  divider(32, 'Module Contracts and Agent-Friendly Structure'),
  content(33, 'A Module Is a Lifecycle Boundary', 'Folders should express ownership, not only reduce file length.', 'cards', ['OWNER|who reviews?', 'LIFECYCLE|what changes?', 'CONTRACT|what crosses?', 'EVIDENCE|what proves?'], 'one boundary · one reason'),
  content(34, 'Five Modules Match Five Responsibilities', 'Storage, queue, state, identity, and logs change differently.', 'pipeline', ['storage', 'messaging', 'job state', 'identity', 'observability'], 'small interfaces connect them', true),
  content(35, 'Typed Inputs Make Decisions Visible', 'Avoid one untyped map containing every setting.', 'compare', ['WEAK INPUT', 'map(any)', 'STRONG INPUT', 'typed + described + validated'], 'errors appear near the contract'),
  content(36, 'Checks Live at Different Times', 'Select the mechanism that can observe the claim.', 'cards', ['VALIDATION|configuration value', 'PRECONDITION|before operation', 'POSTCONDITION|observed result', 'TEST|cross-resource behaviour'], 'no one check proves everything'),
  content(37, 'Outputs Are Public Interfaces', 'Export the narrow identity a caller needs.', 'compare', ['BROAD OUTPUT', 'entire resource object', 'NARROW OUTPUT', 'bucket ARN'], 'sensitive marking reduces display only'),
  content(38, 'Defaults Are Decisions for Every Caller', 'Require explicit input for high-consequence choices.', 'cards', ['SAFE DEFAULT|common low risk', 'EXPLICIT|retention', 'EXPLICIT|public exposure', 'EXPLICIT|deletion'], 'review what the module decides'),
  content(39, 'An Agent Task Follows the Module Boundary', 'Scope, tests, and plan budget align.', 'pipeline', ['named module', 'allowed files', 'contract tests', 'small plan', 'evidence'], 'make the next correct change easy', true),

  divider(40, 'State Is a Trust and Recovery Boundary'),
  content(41, 'State Binds Address to Remote Identity', 'The address is how code remembers one real object.', 'pipeline', ['module.messaging|queue.jobs', 'state binding', 'queue URL'], 'remove the binding ≠ delete the object', true),
  content(42, 'Keep Four Truths Separate', 'Disagreement is a diagnosis, not a reason to edit state quickly.', 'evidence-inputs', ['operator decision', 'configuration', 'state', 'plan', 'remote API'], 'preserve all four before recovery', true),
  content(43, 'Sensitive Values Can Still Enter State', 'Hidden display is not encryption or deletion.', 'compare', ['CLI DISPLAY', 'redacted', 'STATE RECORD', 'may contain value'], 'protect backend + evidence'),
  content(44, 'A Team Backend Needs Four Controls', 'Remote storage alone is not enough.', 'cards', ['ACCESS|least privilege', 'ENCRYPTION|at rest + transit', 'VERSIONS|recover history', 'LOCKING|one writer'], 'locking does not approve a plan'),
  content(45, 'Lineage and Serial Identify State History', 'A filename alone cannot support recovery.', 'pipeline', ['lineage', 'serial', 'workspace', 'config commit', 'provider lock'], 'bind recovery to one history', true),
  content(46, 'Direct State Commands Are Sharp Tools', 'They change bindings without preserving normal intent.', 'compare', ['MOVED BLOCK', 'declarative history', 'state mv / rm', 'direct emergency action'], 'backup + exact target + review'),
  content(47, 'Recovery Reconciles Every View', 'Do not force green before understanding the mismatch.', 'pipeline', ['preserve', 'compare remote', 'choose authority', 'repair binding', 'plan', 'prove convergence'], 'human owns the recovery decision', true),

  divider(48, 'Refactoring Without Recreating Infrastructure'),
  content(49, 'A Rename Changes the Resource Address', 'Without a move, code can imply destroy and create.', 'compare', ['OLD ADDRESS', 'module.queue…', 'NEW ADDRESS', 'module.messaging…'], 'same intent · different identity to Terraform'),
  content(50, 'A moved Block Records Refactor Intent', 'Map the old address to the new address in code.', 'pipeline', ['old address', 'moved block', 'new address', 'same queue'], 'reviewable and repeatable', true),
  content(51, 'The Plan Must Prove No Recreation', 'The words and action counts both matter.', 'compare', ['EXPECTED', 'has moved to', 'BUDGET', '0 create · 0 destroy'], 'remote identity stays stable'),
  content(52, 'Instance Keys Are Part of the Address', 'count to for_each can require an explicit mapping.', 'pipeline', ['count[0]', 'business key', 'moved mapping', 'for_each["jobs"]'], 'stable keys reduce future ambiguity', true),
  content(53, 'Import Binds an Existing Object', 'Configuration must still own every intended attribute.', 'pipeline', ['remote object', 'import block', 'state address', 'post-import plan'], 'review defaults and drift', true),
  content(54, 'state mv Is an Emergency Path', 'Use exact backups and preserve the operator record.', 'approval-gate', ['backup state', 'verify addresses', 'human approval', 'state mv', 'new plan'], 'direct mutation requires extra evidence', true),
  content(55, 'Keep Moves Through the Upgrade Window', 'One successful environment does not represent every starting version.', 'pipeline', ['old release', 'moved block', 'all environments', 'minimum version', 'remove later'], 'compatibility has a time dimension', true),

  divider(56, 'Identity, Secrets, and Least Privilege'),
  content(57, 'Valid Wildcards Are Still Unsafe', 'Schema validity cannot approve broad authority.', 'compare', ['STARTER', 'Action * · Resource *', 'CANDIDATE', 'named actions + ARNs'], 'least privilege needs semantic review'),
  content(58, 'Bind Permissions to Exact Resources', 'Actions and identities must both be narrow.', 'cards', ['S3|bucket + objects', 'SQS|one queue ARN', 'ACTIONS|only required verbs', 'DENY|unrelated resources'], 'review two dimensions'),
  content(59, 'Authority Also Creates Graph Edges', 'Exact module outputs connect identity to its resources.', 'pipeline', ['bucket ARN', 'queue ARN', 'policy document', 'worker role'], 'dependency and security align', true),
  content(60, 'Sensitive Does Not Mean Secret-Free', 'Values can remain in state, provider calls, or outside logs.', 'boundary', ['sensitive output', 'hidden CLI', 'state protected', 'evidence redacted'], 'redact at the source'),
  content(61, 'Deployment and Workload Identity Differ', 'Narrow workload policy does not narrow the IaC runner.', 'compare', ['DEPLOYMENT ID', 'creates infrastructure', 'WORKLOAD ID', 'uses bucket + queue'], 'control both independently'),
  content(62, 'Local Mode Fails Closed', 'Two signals must agree before test credentials are accepted.', 'approval-gate', ['local_mode=true', 'localhost:4566', 'fixed test creds', 'local operation'], 'any mismatch stops before apply', true),

  divider(63, 'Build the Local Cloud Foundation'),
  content(64, 'Eight Resources Support One Workload', 'Every object has a role in the local platform.', 'hub', ['AI workload|foundation', 'S3 × 3', 'SQS × 1', 'DynamoDB × 1', 'IAM × 2', 'Logs × 1'], 'five domains · eight state addresses', true),
  content(65, 'Floci Provides an AWS-Shaped Endpoint', 'The guard permits only the named local target.', 'pipeline', ['Terraform|or OpenTofu', 'AWS provider|6.61.0', 'localhost|4566', 'Floci APIs'], 'no cloud account or paid service', true),
  content(66, 'The Lifecycle Tests More Than Creation', 'Create, refactor, update, converge, and clean up.', 'pipeline', ['8 create', 'direct reads', '1 move', '1 update', 'no change', '8 destroy'], 'complete bounded lifecycle', true),
  content(67, 'Independent Evidence Supports the Result', 'Plan, state, and APIs observe different facts.', 'evidence-inputs', ['lifecycle claim', 'JSON plan', 'state list', 'graph', 'direct APIs', 'cleanup'], 'no single green label carries the claim', true),
  content(68, 'The Measured Profile Is Small', 'Observed peaks support the constrained learner path.', 'compare', ['TERRAFORM', 'Floci peak 36.2 MiB', 'OPENTOFU', 'Floci peak 61.83 MiB'], 'machine observation · not guarantee'),
  content(69, 'Local Proof Has a Clear Boundary', 'Strong evidence remains honest about what it cannot prove.', 'pass-boundary', ['LOCAL PASS', 'not AWS parity', 'not remote state', 'not org policy'], 'add production evidence later'),

  divider(70, 'Small Plans and Reviewable Agent Changes'),
  content(71, 'Plan Actions Are Not Equal', 'One count can hide very different operational risk.', 'cards', ['UPDATE|same identity', 'REPLACE|migration', 'UNKNOWN|missing review fact', 'MOVE|address only'], 'read meaning before totals'),
  content(72, 'Replacement Is a Migration Decision', 'Data, identity, consumers, and rollback must move.', 'pipeline', ['backup', 'create target', 'copy or drain', 'cut over', 'verify', 'delete old'], 'a green plan does not supply migration', true),
  content(73, 'Unknowns Can Cross Approval Boundaries', 'A computed ID is normal; unknown authority may not be.', 'compare', ['EXPECTED UNKNOWN', 'new object ID', 'BLOCKING UNKNOWN', 'policy resource boundary'], 'classify by consequence'),
  content(74, 'Give the Agent a Change Budget', 'Define expected shape before generation.', 'cards', ['FILES|named modules', 'ACTIONS|expected types', 'RESOURCES|maximum count', 'STOP|replacement or escape'], 'unexpected shape stops the run'),
  content(75, 'Reject Noisy Unrelated Diffs', 'Provider upgrades, formatting, and identity edits need separate review.', 'pipeline', ['requested queue', 'derive changed files', 'find unrelated diff', 'split change'], 'agent summary cannot redefine scope', true),
  content(76, 'Review the Four-Signal Challenge', 'Update, replace, unknown, and move need four decisions.', 'test-matrix', ['update in-place', 'replace', 'known after apply', 'moved to'], 'explain approve · redesign · defer'),

  divider(77, 'OpenTofu Compatibility and Migration Record'),
  content(78, 'The Record Binds Exact Inputs and Results', 'Compatibility needs more than a syntax statement.', 'evidence-chain', ['tool versions', 'provider locks', 'graph hashes', 'lifecycle', 'differences', 'approval'], 'one reviewable migration record', true),
  content(79, 'The Two Proven Runs Match in Behaviour', 'They differ in dependency and graph identity.', 'compare', ['TERRAFORM', '8 create · move · update', 'OPENTOFU', '8 create · move · update'], 'both converge and clean up'),
  content(80, 'Migration Transfers Write Authority', 'Compare first; stop the old writer before cutover.', 'pipeline', ['back up', 'target init', 'compare plan', 'stop old writer', 'approve cutover', 'record owner'], 'rollback is decided before mutation', true),
  content(81, 'Own the Whole Infrastructure Lifecycle', 'Evaluate code, graph, provider, state, authority, and evidence.', 'closing', ['typed HCL', 'reviewed graph', 'locked provider', 'protected state', 'small plan', 'human decision'], 'simplify the workflow · keep the engineering', true),
  content(82, 'Build and Review the Local Foundation', 'Repair three defects, run both lifecycles, and judge four plan signals.', 'lab-bridge', ['inspect|starter', 'repair|candidate', 'run|Terraform', 'compare|OpenTofu', 'review|challenge', 'clean up|Floci'], 'the local command is explicit approval for this disposable run', true),
];
