const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Test and Secure AI-Generated Infrastructure Code', subtitle: 'Build evidence before you trust generated HCL.', type: 'pipeline', items: ['generated|candidate', 'cheap|checks', 'rendered|plan', 'security +|cost', 'human|review'], foot: 'plan-only · no apply · one exact candidate', fragments: true, titleSlide: true},

  divider(2, 'The IaC Evidence Pyramid'),
  content(3, 'Generated IaC Starts Untrusted', 'Clean code and confident words are not evidence.', 'compare', ['AGENT OUTPUT', 'plausible HCL', 'REVIEW INPUT', 'untrusted candidate'], 'trust begins after independent checks'),
  content(4, 'Every Check Has a Proof Limit', 'Use each result only for the claim it can observe.', 'cards', ['FORMAT|layout only', 'VALIDATE|schema only', 'PLAN|intended actions', 'RUNTIME|observed behaviour'], 'green is always scoped'),
  content(5, 'The Evidence Pyramid Orders Cost', 'Run fast checks first, then increase understanding.', 'ladder', ['format', 'validate', 'test', 'plan', 'policy', 'human review'], 'higher checks add context · not permission', true),
  content(6, 'Ten Gates Support One Narrow Decision', 'All required observations must point to one candidate.', 'pipeline', ['format +|validate', 'test +|plan', 'lint +|security', 'policy +|cost', 'redaction +|safety', 'ready for|review'], 'READY_FOR_HUMAN_REVIEW · never APPROVED', true),
  content(7, 'Classify Failure Before Repair', 'Different failure classes need different fixes.', 'cards', ['CANDIDATE|bad HCL', 'EVALUATOR|bad check', 'TOOL|could not run', 'EVIDENCE|stale link', 'BOUNDARY|outside scope'], 'name the class and blocking observation'),
  content(8, 'Independent Checks Catch Evaluator Errors', 'A second surface can expose a false green.', 'pipeline', ['unsafe|source', 'green|policy', 'failed policy|unit test', 'inspect real|plan field', 'repair|evaluator'], 'do not weaken the candidate to fix the detector', true),
  content(9, 'Human Review Stays Above the Pipeline', 'Automation prepares a decision; a person owns it.', 'pipeline', ['fixed|gates', 'evidence|bundle', 'human|plan review', 'separate merge|decision', 'separate apply|authority'], 'validation · approval · delivery stay separate', true),

  divider(10, 'Formatting, Validation, and Provider-Aware Checks'),
  content(11, 'Format Proves Layout', 'Canonical HCL is useful and deliberately narrow.', 'compare', ['fmt -check', 'layout is canonical', 'NOT PROVEN', 'security or intent'], 'a fast entry gate'),
  content(12, 'Validate Loads Provider Schema', 'Parsing alone cannot check provider arguments.', 'pipeline', ['HCL|source', 'init|-backend=false', 'provider|schema', 'validate', 'static|result'], 'provider-aware · still plan-free', true),
  content(13, 'Valid Can Still Be Unsafe', 'Correct names and types can carry dangerous values.', 'compare', ['VALID BOOL', 'block_public_acls = false', 'REQUIRED INTENT', 'public access blocked'], 'schema compatibility ≠ acceptable intent'),
  content(14, 'The Lock Binds Provider Identity', 'Source, version, constraints, and hashes travel together.', 'pipeline', ['provider|source', 'selected|version', 'constraint', 'package|hashes'], 'review the generated lock diff', true),
  content(15, 'Record Source and Effective Lock', 'Initialization may rewrite dependency identity.', 'compare', ['SOURCE LOCK', '3db541e4…', 'EFFECTIVE LOCK', 'same or changed'], 'a rewrite is evidence to investigate'),
  content(16, 'Compare Engine Semantics, Not Bytes', 'Terraform and OpenTofu can serialize differently.', 'compare', ['STABLE FACTS', 'addresses + actions', 'EXPECTED DIFFERENCE', 'plan + lock hashes'], 'same behaviour does not require same bytes'),
  content(17, 'Freeze the Plan-Only Command Boundary', 'The runner owns fixed arguments and working paths.', 'boundary', ['plan-only runner', 'fixed argv', 'backend disabled', 'refresh false', 'new /tmp output', 'no apply'], 'the agent cannot expand this boundary'),

  divider(18, 'Terraform Test and Contract Tests'),
  content(19, 'Tests Turn Contracts Into Examples', 'Executable examples protect stable behaviour.', 'pipeline', ['module|contract', 'test|fixture', 'mocked|plan', 'assertions', 'contract|evidence'], 'test the ownership boundary', true),
  content(20, 'Mocked Providers Keep the Lab Local', 'Plan tests need no cloud account or real resource.', 'compare', ['MOCKED PLAN', 'local + disposable', 'REAL APPLY', 'environment authority'], 'the test never crosses into deployment'),
  content(21, 'Assert Behaviour, Not File Layout', 'Stable outcomes survive harmless refactoring.', 'compare', ['WEAK', 'resource is on line 23', 'STRONG', 'public access is blocked'], 'failure messages name the broken contract'),
  content(22, 'Expected Failures Need Exact Controls', 'A green rejection must fail for the intended reason.', 'pipeline', ['invalid|input', 'named|validation', 'expected|failure', 'green test'], 'broad failure matching can hide the wrong error', true),
  content(23, 'Seed a Known Failure', 'A detector earns trust by rejecting a reference defect.', 'pipeline', ['known unsafe|fixture', 'run test', 'observe exact|failure', 'repair', 'observe pass'], 'repeat the mutation after repair', true),
  content(24, 'Protect Evaluators from Self-Repair', 'An agent should not silently weaken its own judge.', 'boundary', ['candidate repair', 'allowed HCL', 'tests frozen', 'policy diff separate', 'human review'], 'source and evaluator ownership stay visible'),
  content(25, 'Tests and Plans Answer Different Questions', 'Keep both because their blind spots differ.', 'compare', ['CONTRACT TEST', 'selected behaviour + mocks', 'RENDERED PLAN', 'full proposed graph'], 'one result cannot replace the other'),

  divider(26, 'Lint and Security Scanning'),
  content(27, 'Linters and Scanners See Different Surfaces', 'Quality rules and security rules overlap only partly.', 'compare', ['TFLINT', 'quality + provider rules', 'TRIVY', 'security check bundle'], 'both results need exact configuration'),
  content(28, 'Scanner Trust Has Five Identities', 'A zero-finding claim needs reproducible inputs.', 'cards', ['TOOL|name + version', 'BUNDLE|version + digest', 'CONFIG|ignore hash', 'SOURCE|candidate hash', 'FINDINGS|rule + location'], 'missing identity makes reuse unsafe'),
  content(29, 'Suppressions Are Reviewed Exceptions', 'An ignore line alone is not a decision record.', 'pipeline', ['rule ID', 'exact scope', 'owner +|reason', 'expiry', 'compensating|evidence'], 'complete metadata still needs judgment', true),
  content(30, 'Ignore IDs Must Match the Registry', 'Two files prevent a quick bypass from looking reviewed.', 'compare', ['trivy.ignore', 'AWS-0089 · 0090 · 0132', 'suppressions.json', 'same three IDs'], 'exact set match · no hidden exception'),
  content(31, 'Triage Findings Before Repair', 'Candidate, rule, bundle, and scope can each be wrong.', 'cards', ['TRUE DEFECT|repair source', 'FALSE POSITIVE|prove mismatch', 'NOT APPLICABLE|review scope', 'TOOL ERROR|fail gate'], 'never turn unavailable into zero findings'),
  content(32, 'Triangulate High-Risk Controls', 'Use independent surfaces for large blast radius.', 'pipeline', ['inspect|source', 'contract|test', 'scanner', 'plan|policy', 'human|review'], 'public access and wildcard IAM need depth', true),
  content(33, 'The Agent Proposes; the Owner Accepts', 'Risk acceptance stays outside the repair loop.', 'pipeline', ['agent triage', 'proposed|suppression', 'control-owner|review', 'scoped|exception'], 'the agent never approves its own exception', true),

  divider(34, 'Policy as Code over Terraform Plans'),
  content(35, 'Policy Reads the Rendered Plan', 'Structured JSON exposes proposed actions and values.', 'pipeline', ['saved|plan', 'show -json', 'Conftest +|Rego', 'policy|result'], 'bind the result to this exact plan', true),
  content(36, 'A Green Policy Can Ask the Wrong Question', 'Engine health does not prove control coverage.', 'compare', ['REAL FIELD', 'block_public_acls', 'FAULTY RULE', 'after.acl'], 'valid Rego · wrong schema path'),
  content(37, 'Missing Fields Produce False Confidence', 'Undefined can prevent a deny rule from matching.', 'pipeline', ['wrong field', 'undefined', 'no deny|result', 'Conftest|exit 0', 'unsafe plan|remains'], 'false green = evaluator failure', true),
  content(38, 'Test Every Policy Branch', 'Allowed, denied, unknown, and malformed inputs all matter.', 'cards', ['ALLOW|known safe', 'DENY|each unsafe field', 'UNKNOWN|explicit outcome', 'MALFORMED|fail clearly'], 'unit tests protect the control contract'),
  content(39, 'Unknown Is Not False', 'Choose indeterminate behaviour by consequence.', 'compare', ['NORMAL UNKNOWN', 'new object ID', 'BLOCKING UNKNOWN', 'IAM resource boundary'], 'missing · null · unknown stay distinct'),
  content(40, 'Bind Policy to Plan and Evaluator', 'A result is reusable only with matching identities.', 'pipeline', ['plan|SHA', 'policy bundle|SHA', 'engine|version', 'unit-test|result', 'decision'], 'stale evidence stops promotion', true),
  content(41, 'Evaluator Changes Need Separate Review', 'Repair the judge without hiding its diff.', 'pipeline', ['isolated|branch', 'policy|diff', 'negative|fixtures', 'human|review', 'accepted|evaluator'], 'independence grows with risk', true),

  divider(42, 'Secrets, Logs, and Evidence Redaction'),
  content(43, 'Minimize Before You Redact', 'The safest secret is the value never collected.', 'pipeline', ['short-lived|credential', 'scoped|injection', 'bounded|command', 'selected|output'], 'redaction is the second control', true),
  content(44, 'Redact Before Storage or Model Context', 'Removing a secret later leaves copies behind.', 'pipeline', ['raw tool|stream', 'redaction|boundary', 'small log|tail', 'evidence|report', 'model|summary'], 'the raw value never enters retained artifacts', true),
  content(45, 'Sensitive Does Not Mean Removed', 'Terraform can hide display while retaining the value.', 'compare', ['CLI DISPLAY', 'redacted', 'PLAN OR STATE', 'value may remain'], 'protect artifacts and select bounded views'),
  content(46, 'Keep Evidence Small and Useful', 'Record decisions without building a data lake.', 'cards', ['COMMAND|fixed argv', 'EXIT|literal status', 'TIME|duration', 'OUTPUT|bounded + redacted', 'ARTIFACT|hash link'], 'retain only what supports review'),
  content(47, 'Tool Output Is Untrusted Data', 'Logs and docs cannot expand agent authority.', 'pipeline', ['tool output', 'possible|instruction', 'treat as data', 'repository|policy', 'bounded|decision'], 'retrieved text never overrides controls', true),
  content(48, 'Test Redaction with Fake Secrets', 'A known marker proves the retained path is filtered.', 'pipeline', ['fake token', 'raw fixture', 'redactor', 'stored log', 'literal absent'], 'record the redaction count', true),
  content(49, 'Map Every Secret Exposure Path', 'Know which process, store, and person can read each value.', 'hub', ['secret source', 'tool process', 'terminal', 'evidence', 'model context', 'PR comment', 'human reviewer'], 'access and retention are separate controls'),

  divider(50, 'Cost and FinOps Gates for IaC'),
  content(51, 'Static FinOps Starts Without Prices', 'Local structure catches useful cost signals early.', 'cards', ['COUNT|resource budget', 'CLASS|approved types', 'OWNER|required tag', 'REGION|allowed location', 'LIFECYCLE|retention'], 'no API key needed for the core gate'),
  content(52, 'The Starter Exceeds the Resource Budget', 'One unused Elastic IP makes six instead of five.', 'compare', ['STARTER', '6 resources + EIP', 'CANDIDATE', '5 approved resources'], 'small counts support human review'),
  content(53, 'Ownership Tags Need Real Owners', 'A non-empty string can still be meaningless.', 'compare', ['WEAK VALUE', 'Owner = team', 'USEFUL VALUE', 'mapped service owner'], 'connect tags to a source of truth'),
  content(54, 'Estimates Depend on Assumptions', 'Version, prices, usage, and currency shape the number.', 'cards', ['TOOL|version', 'PRICE DATA|date', 'USAGE|assumption', 'CURRENCY|context'], 'an estimate is decision support · not an invoice'),
  content(55, 'Match Cost Gates to Change Class', 'Different changes need different financial context.', 'cards', ['ELASTIC IP|reason + owner', 'DATABASE|monthly delta', 'LOGS|ingest + retention', 'DELETE|cost + data risk'], 'cheapest is not automatically correct'),
  content(56, 'Bind Cost Evidence to the Plan', 'Any source change can invalidate an estimate.', 'pipeline', ['plan|SHA', 'static|facts', 'optional|estimate', 'unknowns +|assumptions', 'FinOps|review'], 'invented numbers are not evidence', true),
  content(57, 'Human Review Owns the Trade-off', 'The agent can calculate; the owner accepts impact.', 'pipeline', ['agent finds|cost signal', 'smaller|option', 'business +|reliability context', 'human|decision'], 'budget authority stays human', true),

  divider(58, 'Adversarial Tasks and Agent Safety Evals'),
  content(59, 'Evaluate the Path, Not Only the HCL', 'Correct output can still come from an unsafe workflow.', 'compare', ['FUNCTIONAL RESULT', 'valid repaired HCL', 'SAFETY RESULT', 'scope + tools + truth'], 'both dimensions must pass'),
  content(60, 'Six Attack Classes Test the Boundary', 'The fixture is inert; the requested actions are not run.', 'cards', ['OVERRIDE|instructions', 'PROTECTED|file edit', 'ENVIRONMENT|apply', 'NETWORK|upload', 'APPROVAL|bypass', 'TRUTH|false pass'], 'recognize and reject every class'),
  content(61, 'Fixed Arguments Beat Forbidden Strings', 'Mechanical allowlists reduce equivalent bypasses.', 'pipeline', ['approved|tool', 'fixed argv', 'scoped cwd', 'timeout', 'captured|exit'], 'shell false · no hidden command expansion', true),
  content(62, 'Negative Cases Prove the Safety Gate', 'Seed safe violations and observe exact rejection.', 'cards', ['FORBIDDEN FILE|reject', 'DANGEROUS ARG|reject', 'NEW IGNORE|reject', 'FAKE SECRET|redact'], 'a gate that never fails may see nothing'),
  content(63, 'Retries Need Stop Conditions', 'A bounded repair loop returns control on uncertainty.', 'loop', ['inspect', 'propose', 'edit scope', 'run gates', 'observe', 'stop or repair'], 'limit retries · preserve failed evidence', true),
  content(64, 'Infrastructure and Evaluator Scope Stay Separate', 'A repair must not silently change its own rules.', 'compare', ['CANDIDATE FILES', 'three reviewed repairs', 'EVALUATOR FILES', 'unchanged hash'], 'separate diffs make independence reviewable'),
  content(65, 'Return Control When Authority Must Expand', 'Policy conflict and new permissions stop automation.', 'pipeline', ['repeated|failure', 'tool|uncertainty', 'scope|conflict', 'authority|request', 'human|decision'], 'do not improvise broader access', true),

  divider(66, 'Evidence Bundles and Operator Plan Review'),
  content(67, 'One Evidence Bundle Represents One Candidate', 'Every observation belongs to one exact run.', 'pipeline', ['source', 'evaluators', 'tools +|locks', 'rendered|plan', 'gate|observations', 'review|decision'], 'a compact decision record', true),
  content(68, 'Four Hashes Prevent Stale Reuse', 'Identity links stop results moving between candidates.', 'cards', ['SOURCE|0b9fe15b…', 'EVALUATOR|a4fd12ba…', 'PLAN|b47ef9a0…', 'LOCK|3db541e4…'], 'matching hashes are necessary · not sufficient'),
  content(69, 'Hashes Prove Identity, Not Correctness', 'A faulty policy can have a perfect stable hash.', 'compare', ['BYTE IDENTITY', 'same artifact', 'ENGINEERING CLAIM', 'fit for this control'], 'signatures add authenticity · not judgment'),
  content(70, 'Review the Human-Readable Plan', 'Read consequence, not only the green summary.', 'cards', ['ACTIONS|replace + delete', 'AUTHORITY|IAM + public', 'UNKNOWN|approval boundary', 'SCOPE|unrelated diff', 'LIFECYCLE|data + rollback'], 'compare the plan with the task request'),
  content(71, 'Use Three Practical Review Outcomes', 'Decision language keeps authority explicit.', 'cards', ['REPAIR REQUIRED|blocker remains', 'READY FOR REVIEW|evidence complete', 'RISK ACCEPTED|named owner'], 'none of these silently means apply'),
  content(72, 'Compare Terraform and OpenTofu Honestly', 'Stable facts can match while dependency identity differs.', 'compare', ['TERRAFORM', '5 addresses · lock 3db541e4…', 'OPENTOFU', '5 addresses · lock 5be4dc35…'], 'separate bundles · same human boundary'),
  content(73, 'Preserve Rejected and Repaired Evidence', 'The failure proves detection; the repair proves this run.', 'pipeline', ['rejected|starter', 'blocking|observations', 'three-file|repair', 'ten green|gates', 'human|review'], 'history becomes a regression fixture', true),

  content(74, 'Review Evidence Before You Trust Generated IaC', 'Test the candidate, the evaluator, and the workflow.', 'pipeline', ['untrusted|candidate', 'independent|gates', 'typed|evidence', 'human|decision'], 'simple workflow · deep engineering · honest boundary', true, false),
  content(75, 'Build the Ten-Gate Evidence Pipeline', 'Reject, repair, compare, review, and clean up.', 'icons', ['inspect|starter', 'run rejected|baseline', 'repair three|files', 'run both|engines', 'review|evidence', 'clean marked|runs'], 'the lab remains plan-only', true),
];
