const divider = (n, title) => ({n, title, divider: true});
const content = (n, title, subtitle, type, items, foot = '', fragments = false) => ({n, title, subtitle, type, items, foot, fragments});

export const slides = [
  {n: 1, title: 'Deploy Applications with Kubernetes, Helm, and AI Agents', subtitle: 'Prove one exact package from source through runtime.', type: 'pipeline', items: ['client|request', 'API', 'dependencies', 'worker', 'result'], foot: 'job-0001 becomes MOCK INFERENCE: HELLO PLATFORM', fragments: true, titleSlide: true},

  divider(2, 'Kubernetes in the Agentic IaC Project'),
  content(3, 'Four Layers Own Different Change Cycles', 'Each setting needs one primary owner.', 'cards', ['TERRAFORM|cluster + cloud', 'HELM|workload package', 'APPLICATION|ports + jobs', 'GITOPS|promotion later'], 'one owner per lifecycle'),
  content(4, 'One Writer Owns Each Setting', 'Two reconcilers can keep undoing each other.', 'compare', ['ONE WRITER', 'Helm owns Deployment', 'TWO WRITERS', 'Terraform + Helm drift'], 'shared reference is not shared write authority'),
  content(5, 'Three Roles Form One Workload', 'One small image, three separate runtime jobs.', 'hub', ['three-role|workload', 'dependencies|queue + result', 'API|port 8080', 'worker|poll + complete', 'API|NodePort', 'dependency|ClusterIP'], 'API -> dependencies -> worker -> result', true),
  content(6, 'Agents Work Inside a Reviewed Package', 'READY_FOR_HUMAN_REVIEW is not approval.', 'boundary', ['bounded chart repair', 'inspect + propose', 'three owned files', 'fixed validators', 'human credential owner', 'human deployment authority'], 'agents verify · humans approve'),
  content(7, 'Evidence Follows the Owner', 'Each observation belongs to one layer.', 'cards', ['PLATFORM|plan + policy', 'PACKAGE|render + release', 'APP|tests + image', 'PROMOTION|sync status', 'RUNTIME|conditions + logs'], 'use evidence only for what it observed'),

  divider(8, 'Desired State and Kubernetes Control Loops'),
  content(9, 'Desired State Becomes Observed State', 'Kubernetes uses narrow control loops.', 'pipeline', ['object|spec', 'API|admission', 'controller', 'scheduler', 'kubelet', 'status'], 'acceptance is only the first observation', true),
  content(10, 'API Acceptance Is Not Runtime Success', 'Valid objects can still fail after storage.', 'compare', ['API ACCEPTED', 'shape + authority passed', 'RUNTIME FAILED', 'image, mount, probe, path'], 'stored is not serving'),
  content(11, 'Each Kubernetes Component Has One Job', 'Read status from the component that owns it.', 'cards', ['DEPLOYMENT|ReplicaSet progress', 'REPLICASET|desired Pods', 'SCHEDULER|node binding', 'KUBELET|container + probes', 'ENDPOINTSLICE|ready backends'], 'one control loop · one narrow report'),
  content(12, 'Generation Binds Status to Intent', 'Status must describe the current desired state.', 'pipeline', ['generation|4', 'controller|observes', 'observedGeneration|4', 'condition +|reason + time'], 'old status cannot prove new intent', true),
  content(13, 'Running, Ready, Endpoint, and Response Differ', 'Four layers must line up for a client.', 'ladder', ['Running', 'Ready=True', 'EndpointSlice|ready', 'HTTP 200'], 'process -> traffic eligibility -> client result', true),

  divider(14, 'Workload Contracts for the API and Worker'),
  content(15, 'One Image Runs Three Roles', 'ROLE selects a separate application boundary.', 'cards', ['DEPENDENCIES|queue + result', 'API|submit + read', 'WORKER|poll + complete'], '3,241,788 bytes · arm64 course image'),
  content(16, 'The API Owns the Synchronous Boundary', 'Submit work now and read the result later.', 'pipeline', ['validate|request', 'enqueue|job-0001', 'return|job ID', 'read|later'], 'the API does not run inference work', true),
  content(17, 'The Worker Owns the Asynchronous Boundary', 'Polling and completion need retry safety.', 'pipeline', ['poll', 'claim|job-0001', 'process', 'complete', 'retry|bounded'], 'the queue contract owns duplicate prevention', true),
  content(18, 'Job 0001 Moves from Queued to Complete', 'The exact request path stays visible.', 'pipeline', ['client|hello platform', 'API|queued', 'dependency|queue', 'worker|process', 'dependency|result', 'client|complete'], 'MOCK INFERENCE: HELLO PLATFORM', true),
  content(19, 'Configuration and Credentials Use Different Paths', 'A URL is config; a token is credential material.', 'compare', ['CONFIGMAP', 'BACKEND_URL', 'PROJECTED SECRET', 'read-only token file'], '/var/run/secrets/inference/token'),
  content(20, 'Health and Readiness Answer Different Questions', 'A healthy process can be unready.', 'compare', ['/healthz', 'process should keep running', '/readyz', 'role can serve now'], 'dependency loss removes traffic without restart'),
  content(21, 'Retry, Idempotency, and Shutdown Share One Contract', 'One job identity survives each state change.', 'loop', ['bounded|retry', 'job-0001|idempotency', 'safe|claim', 'record|completion', 'shutdown|state'], 'startup, duplicate delivery, and termination stay safe', true),

  divider(22, 'Helm Chart Structure and Values Contracts'),
  content(23, 'A Helm Chart Has Six Review Surfaces', 'Review package identity, inputs, and output.', 'cards', ['Chart.yaml|package version', 'values.yaml|safe defaults', 'values.schema.json|input contract', 'templates/|resource design', '_helpers.tpl|names + labels', 'tests/|narrow smoke checks'], 'a chart is a supported product interface'),
  content(24, 'Helm Values Merge in Precedence Order', 'Preserve the exact merged release intent.', 'pipeline', ['defaults', 'reviewed|values file', 'narrow|override', 'JSON Schema', 'templates', 'render'], 'later values win', true),
  content(25, 'Values Schema Is Not Runtime Policy', 'Types cannot prove target-cluster facts.', 'compare', ['SCHEMA PROVES', 'type + range + required', 'RUNTIME MUST PROVE', 'Secret exists + resources fit'], 'safe shape is not runtime fitness'),
  content(26, 'Chart Version and Application Version Differ', 'Package and software can change independently.', 'cards', ['CHART VERSION|templates + defaults', 'APP VERSION|software release', 'IMAGE DIGEST|immutable identity'], 'record all three for a production release'),
  content(27, 'Helm History Does Not Guarantee Safe Rollback', 'External state may not move back with a revision.', 'boundary', ['release revision', 'data compatibility', 'Secret changed', 'dependency changed', 'hook side effect', 'image availability'], 'define application and data recovery first'),

  divider(28, 'Helm Templates versus Kustomize Overlays'),
  content(29, 'Helm Packages Inputs; Kustomize Patches Objects', 'Choose the model that keeps changes reviewable.', 'compare', ['HELM', 'templates + values + history', 'KUSTOMIZE', 'complete base + visible patches'], 'neither tool is automatically production ready'),
  content(30, 'Two Transformation Stages Increase Review Work', 'Stack tools only when ownership requires it.', 'pipeline', ['Helm|render', 'Kustomize|patch', 'final|render', 'schema +|policy'], 'preserve source, intermediate, patch, and final output', true),
  content(31, 'Ownership Decides the Delivery Model', 'A clean patch can still cross a boundary.', 'cards', ['PLATFORM TEAM|supported chart', 'APP TEAM|bounded values', 'ENV TEAM|namespace overlay'], 'probe and port ownership stays with the app contract'),
  content(32, 'Final Render Is the Shared Review Artifact', 'Both delivery models end at exact objects.', 'hub', ['final|render', 'Helm|source', 'Kustomize|source', 'schema|checks', 'policy|checks'], 'review and test what delivery will use', true),

  divider(33, 'Render-First Validation and Chart Tests'),
  content(34, 'Source, Render, API, and Runtime Are Separate Layers', 'Each layer supports a different statement.', 'pipeline', ['chart|source', 'exact|render', 'API|admission', 'controller|status', 'runtime|request'], 'render evidence does not predict runtime', true),
  content(35, 'Lint and Render Can Both Miss Unsafe Design', 'The real starter passed both structural checks.', 'compare', ['GREEN TOOLS', 'lint 0 + render 0', 'UNSAFE DESIGN', 'token committed + limits absent'], 'structure passed · package rejected'),
  content(36, 'Thirteen Gates Review One Exact Candidate', 'All required checks bind to the same source.', 'cards', ['APP + LINT|behaviour + chart', 'RENDER + SCHEMA|exact objects', 'KUBECONFORM|API shape', 'SECRET + LIMITS|static safety', 'CONFTEST + CONTRACT|written rules', 'PROBES + ROLES|workload boundary'], '13 gates -> READY_FOR_HUMAN_REVIEW'),
  content(37, 'The Accepted Render Contains Nine Objects', 'Measured identity keeps the review reproducible.', 'cards', ['SOURCE SHA|ba361529...', 'RENDER|9 objects', 'SIZE|10,617 bytes', 'RENDER SHA|76be5320...'], 'hash identity is not correctness'),
  content(38, 'Golden Files and Semantic Assertions Catch Different Drift', 'Use readable snapshots and focused checks.', 'compare', ['GOLDEN RENDER', 'whole output drift', 'SEMANTIC TEST', 'exact security field'], 'large snapshots can hide one important change'),
  content(39, 'Dry Run and Chart Tests Add Narrow Runtime Evidence', 'Each higher check observes one more layer.', 'ladder', ['server|dry-run', 'chart|smoke test', 'full workload|request'], 'HTTP 200 proves only the tested path', true),
  content(40, 'The Agent Must Not Repair Its Own Evaluator', 'Chart and judge changes need separate review lanes.', 'boundary', ['chart candidate', 'three owned files', 'evaluator frozen', 'policy diff separate', 'known-bad fixture', 'human review'], 'a changed judge must still reject the defect'),

  divider(41, 'Service Accounts, RBAC, and Secrets'),
  content(42, 'Each Role Gets Its Own ServiceAccount', 'Separate identities keep later bindings reviewable.', 'cards', ['DEPENDENCIES|ServiceAccount', 'API|ServiceAccount', 'WORKER|ServiceAccount'], 'no shared default identity'),
  content(43, 'No API Call Means No Pod API Token', 'Least privilege can start with absence.', 'compare', ['SERVICEACCOUNT', 'automount false', 'POD SPEC', 'automount false'], 'none of the three roles calls the Kubernetes API'),
  content(44, 'RBAC Controls Kubernetes API Calls Only', 'Other access paths need other controls.', 'cards', ['RBAC|API verbs', 'NETWORK|Service traffic', 'FILESYSTEM|mounted token', 'CLOUD|workload identity'], 'RBAC cannot fix dependency traffic'),
  content(45, 'ConfigMap URL and Secret Token Stay Separate', 'Keep token material outside Helm and Git.', 'compare', ['CONFIGMAP PATH', 'URL appears in render', 'SECRET PATH', 'name + key only'], 'projected read-only file · no token value'),
  content(46, 'Secret Rotation Needs an Application Test', 'Object change alone does not prove new access.', 'pipeline', ['Secret|updated', 'projected|file refresh', 'app|rereads', 'new token|works', 'old token|rejected'], 'rotation needs positive and negative evidence', true),

  divider(47, 'Probes, Resources, and Graceful Shutdown'),
  content(48, 'Startup, Readiness, and Liveness Have Different Effects', 'Probe choice is a recovery decision.', 'cards', ['STARTUP|initialization done?', 'READINESS|serve traffic now?', 'LIVENESS|restart process?'], 'one endpoint should not answer every question'),
  content(49, 'Dependency-Aware Readiness Protects Traffic', 'A process may live while its role is unavailable.', 'compare', ['HEALTHY PROCESS', '/healthz HTTP 200', 'UNREADY ROLE', 'dependency path failed'], 'remove traffic without a restart storm'),
  content(50, 'Probe Timing Creates a Detection Window', 'Period and threshold shape removal time.', 'pipeline', ['period|3 s', 'timeout|1 s', 'threshold|3', 'ready=false'], 'scheduler and network timing add variation', true),
  content(51, 'The Mock Uses an Exact Resource Contract', 'Every role has requests and limits.', 'cards', ['CPU REQUEST|10m', 'MEM REQUEST|32Mi', 'CPU LIMIT|100m', 'MEM LIMIT|64Mi'], 'bounded mock · not model-server sizing'),
  content(52, 'CPU Throttling and Memory OOM Differ', 'A resource field needs runtime interpretation.', 'compare', ['CPU LIMIT', 'throttling + delay', 'MEMORY LIMIT', 'OOM kill + restart'], 'a green render proves only that the budget exists'),
  content(53, 'Pod QoS Includes Every Container', 'One sidecar changes the complete Pod class.', 'boundary', ['Pod resource boundary', 'app requests', 'app limits', 'sidecar requests', 'sidecar limits', 'scheduler + QoS'], 'measure representative traffic'),
  content(54, 'Graceful Worker Shutdown Is a Queue Sequence', 'Termination must preserve job safety.', 'pipeline', ['remove from|endpoints', 'stop|polling', 'finish or|return job', 'record|state', 'exit within|grace'], 'grace time alone cannot make work idempotent', true),

  divider(55, 'Network Policy and Namespace Boundaries'),
  content(56, 'The Workload Needs Three Traffic Paths and DNS', 'Required flows come before policy YAML.', 'hub', ['required|flows', 'client -> API|8080', 'API -> dependency|8081', 'worker -> dependency|8081', 'cluster|DNS'], 'default deny must preserve every required path', true),
  content(57, 'NetworkPolicy Selection Is Additive', 'One broad allow can reopen intended denial.', 'cards', ['INGRESS|who reaches Pod', 'EGRESS|where Pod connects', 'ADDITIVE|all allows combine'], 'selectors define the subjects'),
  content(58, 'DNS Rules Depend on the Target Cluster', 'Portable intent meets CNI-specific labels.', 'compare', ['POLICY INTENT', 'DNS must remain reachable', 'TARGET CLUSTER', 'labels + TCP/UDP + NodeLocal'], 'inspect the supported data plane'),
  content(59, 'Enforcement Proof Needs Positive and Negative Traffic', 'Test both sources against one ready destination.', 'pipeline', ['policy|intent', 'live|subjects', 'ready|destination', 'allowed|source works', 'denied|source fails', 'CNI + DNS|evidence'], 'timeout alone is weak denial evidence', true),
  content(60, 'The Core Kind Run Proves No NetworkPolicy Denial', 'NetworkPolicy was disabled in the measured profile.', 'compare', ['DEFAULT KIND', 'required connectivity worked', 'ENFORCING CNI', 'allow + deny not tested'], 'default Kind connectivity only · rendered policy is intended configuration · no enforcement claim'),

  divider(61, 'Run the Workload on a Small Kind Cluster'),
  content(62, 'The Runtime Boundary Is Exact and Disposable', 'Cleanup owns these names and nothing broader.', 'cards', ['CLUSTER|agentic-iac-s9', 'CONTEXT|kind-agentic-iac-s9', 'NAMESPACE|inference', 'RELEASE|inference-platform', 'HOST|127.0.0.1:18080', 'NODEPORT|30080'], 'dependency port 8081 · one Kind node'),
  content(63, 'Build, Load, Install, Observe, and Clean Up', 'Reject the starter before runtime begins.', 'pipeline', ['build|image', 'create|Kind', 'load|image', 'install|Helm', 'observe|job', 'exact|cleanup'], 'one reviewed release · one bounded run', true),
  content(64, 'Three Deployments and Two Services Become Ready', 'The live release exposes both required paths.', 'hub', ['live|release', 'dependencies|1/1 Running', 'API|1/1 Running', 'worker|1/1 Running', 'NodePort|8080:30080', 'ClusterIP|8081'], 'zero restarts · ready endpoints', true),
  content(65, 'The Exact Job Flow Completes Once', 'Queued and complete were directly observed.', 'pipeline', ['health|HTTP 200', 'ready|HTTP 200', 'POST|job-0001', 'queued', 'worker|complete', 'result|returned'], 'running passed between 50 ms polls', true),
  content(66, 'Three Lifecycles Finished in Under 50 Seconds', 'Measured local runs, not universal promises.', 'cards', ['COLD|49.630 s', 'WARM 1|45.698 s', 'WARM 2|48.547 s'], 'each total includes exact cleanup'),
  content(67, 'Named-Node Memory Stayed Below 672 MiB', 'Configured capacity is a different fact.', 'cards', ['COLD|656.2 MiB', 'WARM 1|671.1 MiB', 'WARM 2|643.1 MiB', 'IMAGE|3,241,788 bytes'], 'Docker capacity 7.744 GiB · node working set measured'),
  content(68, 'Cleanup Is Part of the Runtime Proof', 'Absence checks close the experiment.', 'pipeline', ['Helm release|absent', 'namespace|absent', 'cluster|absent', 'node container|absent', 'context|absent'], 'unrelated clusters remain untouched', true),

  divider(69, 'Diagnose Generated Kubernetes Failures'),
  content(70, 'Move from Render to the Exact Client Path', 'Stop at the first layer with failing evidence.', 'pipeline', ['render +|values', 'controller|status', 'Pod +|probe', 'EndpointSlice', 'live object', 'role logs', 'client|request'], 'diagnosis follows evidence order', true),
  content(71, 'A Wrong Readiness Path Returns HTTP 404', 'The old ready Pod can hide the new failure.', 'pipeline', ['live path|/ready', 'new Pod|0/1', 'probe event|HTTP 404', 'mixed|endpoints', 'render path|/readyz'], 'live drift · not a Helm render defect', true),
  content(72, 'An Unreachable Backend Returns HTTP 503', 'A ready dependency narrows the worker fault.', 'pipeline', ['wrong DNS|name', 'worker|0/1', 'readiness|HTTP 503', 'dependency|ready', 'log|no such host'], 'restore the reviewed ConfigMap reference', true),
  content(73, 'A Wrong NodePort Breaks Only the Host Path', 'Healthy Pods do not prove the host mapping.', 'compare', ['CLUSTER PATH', 'Pod + endpoint ready', 'HOST PATH', 'Service 30081 · Kind 30080'], 'wrong Helm value · not Pod readiness'),
  content(74, 'Rolling Updates Can Hide a Failed New Pod', 'Available can remain true through the old revision.', 'cards', ['OLD POD|1/1 ready', 'NEW POD|0/1 unready', 'ENDPOINTSLICE|ready true + false'], 'attach every observation to a Pod revision'),
  content(75, 'A Diagnosis Record Has Five Parts', 'Make every conclusion reviewable.', 'cards', ['SYMPTOM|user sees', 'LAST HEALTHY|layer', 'FIRST FAILURE|direct evidence', 'EXPLAINING FIELD|source or live', 'SMALLEST REPAIR|bounded'], 'name object, revision, observation, and time'),
  content(76, 'Recovery Repeats the Failed Check and Full Path', 'Agent confidence is not recovery evidence.', 'pipeline', ['smallest|repair', 'rollout|recovers', 'endpoint|ready', 'HTTP 200', 'job|complete'], 'rerun the original failure and end-to-end path', true),

  content(77, 'Review the Render, Then Prove the Runtime', 'Static evidence, runtime proof, and approval stay separate.', 'pipeline', ['reviewed|package', '13 static|gates', 'real control|loops', 'human|authority'], 'one exact candidate · one honest proof boundary', true),
  content(78, 'Repair and Run the Helm Package on Kind', 'Inspect, repair, run, diagnose, and clean up.', 'icons', ['inspect +|reject', 'repair three|files', 'render +|review', 'run on|Kind', 'diagnose|evidence', 'exact|cleanup'], 'local only · NetworkPolicy disabled'),
];
